export default defineEventHandler(async (event) => {
  const config = useRuntimeConfig()
  if (config.mockEnabled) {
    return [
      {
        cid: '555745',
        nodeid: '657',
        status: 'Pending',
        userid: '19831',
        sysName: 'OA',
        isremark: '0',
        userName: 'shu yaojin',
        usertype: '0',
        viewtype: '-2',
        agenttype: '0',
        creatorId: '26085',
        requestId: '506594',
        createTime: '2025-10-17 16:31:06',
        isbereject: '',
        creatorName: 'Developer 1',
        isprocessed: '',
        operateTime: '2026-04-20 14:46:48',
        preisremark: '0',
        receiveTime: '2025-10-17 16:31:06',
        requestName: 'ICSA BU Group Summary Report Submission Flow-Developer 1-2025-10-17',
        requestmark: 'ICSA2025375',
        takisremark: '',
        requestLevel: '0',
        currentNodeId: '657',
        lastOperatorId: '26085',
        currentNodeName: 'Upload and submit Report Outline',
        currentnodetype: '2',
        lastOperateTime: '2025-10-17 16:31:06',
        agentorbyagentid: '-1',
        lastOperatorName: 'Developer 1',
        userDepartmentId: '33861',
        userSubcompanyId: '280',
        workflowBaseInfo: {
          formId: '-330',
          workflowId: '111',
          workflowName: 'ICSA BU Group Summary Report Submission Flow',
          workflowTypeId: '47',
          workflowTypeName: 'GICRM - Internal Control Self-Assessment',
        },
        userDepartmentName: 'DCHBI',
        userSubcompanyName: 'Operation',
        creatorDepartmentId: '3255',
        creatorSubcompanyId: '262',
        creatorDepartmentName: 'Prof Svc-Low Code Platform',
        creatorSubcompanyName: 'Others Business',
      },
      {
        cid: '555723',
        nodeid: '616',
        status: 'Review by GICRM',
        userid: '19831',
        sysName: 'OA',
        isremark: '0',
        userName: 'shu yaojin',
        usertype: '0',
        viewtype: '0',
        agenttype: '0',
        creatorId: '26085',
        requestId: '506592',
        createTime: '2025-10-17 16:20:37',
        isbereject: '',
        creatorName: 'Developer 1',
        isprocessed: '',
        operateTime: ' ',
        preisremark: '0',
        receiveTime: '2025-10-17 16:20:37',
        requestName: 'ICSA Main Process-Developer 1-2025-10-17',
        requestmark: 'ICSA2025374',
        takisremark: '',
        requestLevel: '0',
        currentNodeId: '616',
        lastOperatorId: '26085',
        currentNodeName: 'Submit Assessment Request',
        currentnodetype: '2',
        lastOperateTime: '2025-10-17 16:20:37',
        agentorbyagentid: '-1',
        lastOperatorName: 'Developer 1',
        userDepartmentId: '33861',
        userSubcompanyId: '280',
        workflowBaseInfo: {
          formId: '-322',
          workflowId: '106',
          workflowName: 'ICSA Main Process',
          workflowTypeId: '47',
          workflowTypeName: 'GICRM - Internal Control Self-Assessment',
        },
        userDepartmentName: 'DCHBI',
        userSubcompanyName: 'Operation',
        creatorDepartmentId: '3255',
        creatorSubcompanyId: '262',
        creatorDepartmentName: 'Prof Svc-Low Code Platform',
        creatorSubcompanyName: 'Others Business',
      },
      {
        cid: '555692',
        nodeid: '682',
        status: 'Generate QC',
        userid: '19831',
        sysName: 'OA',
        isremark: '0',
        userName: 'shu yaojin',
        usertype: '0',
        viewtype: '0',
        agenttype: '0',
        creatorId: '26085',
        requestId: '506590',
        createTime: '2025-10-17 15:24:41',
        isbereject: '',
        creatorName: 'Developer 1',
        isprocessed: '',
        operateTime: ' ',
        preisremark: '0',
        receiveTime: '2025-10-17 15:24:41',
        requestName: 'ICSA Entity Assessment & Quality Check Flow-Developer 1-2025-10-17',
        requestmark: 'ICSA20250438',
        takisremark: '',
        requestLevel: '0',
        currentNodeId: '682',
        lastOperatorId: '26085',
        currentNodeName: 'Quality Check',
        currentnodetype: '2',
        lastOperateTime: '2025-10-17 15:24:41',
        agentorbyagentid: '-1',
        lastOperatorName: 'Developer 1',
        userDepartmentId: '33861',
        userSubcompanyId: '280',
        workflowBaseInfo: {
          formId: '-323',
          workflowId: '107',
          workflowName: 'ICSA Entity Assessment & Quality Check Flow',
          workflowTypeId: '47',
          workflowTypeName: 'GICRM - Internal Control Self-Assessment',
        },
        userDepartmentName: 'DCHBI',
        userSubcompanyName: 'Operation',
        creatorDepartmentId: '3255',
        creatorSubcompanyId: '262',
        creatorDepartmentName: 'Prof Svc-Low Code Platform',
        creatorSubcompanyName: 'Others Business',
      },
      {
        cid: '555646',
        nodeid: '657',
        status: 'Pending',
        userid: '19831',
        sysName: 'OA',
        isremark: '0',
        userName: 'shu yaojin',
        usertype: '0',
        viewtype: '0',
        agenttype: '0',
        creatorId: '26085',
        requestId: '506587',
        createTime: '2025-10-17 14:40:27',
        isbereject: '',
        creatorName: 'Developer 1',
        isprocessed: '',
        operateTime: ' ',
        preisremark: '0',
        receiveTime: '2025-10-17 14:40:27',
        requestName: 'ICSA BU Group Summary Report Submission Flow-Developer 1-2025-10-17',
        requestmark: 'ICSA2025373',
        takisremark: '',
        requestLevel: '0',
        currentNodeId: '657',
        lastOperatorId: '26085',
        currentNodeName: 'Upload and submit Report Outline',
        currentnodetype: '2',
        lastOperateTime: '2025-10-17 14:40:27',
        agentorbyagentid: '-1',
        lastOperatorName: 'Developer 1',
        userDepartmentId: '33861',
        userSubcompanyId: '280',
        workflowBaseInfo: {
          formId: '-330',
          workflowId: '111',
          workflowName: 'ICSA BU Group Summary Report Submission Flow',
          workflowTypeId: '47',
          workflowTypeName: 'GICRM - Internal Control Self-Assessment',
        },
        userDepartmentName: 'DCHBI',
        userSubcompanyName: 'Operation',
        creatorDepartmentId: '3255',
        creatorSubcompanyId: '262',
        creatorDepartmentName: 'Prof Svc-Low Code Platform',
        creatorSubcompanyName: 'Others Business',
      },
      {
        cid: '555131',
        nodeid: '657',
        status: 'Pending',
        userid: '19831',
        sysName: 'OA',
        isremark: '0',
        userName: 'shu yaojin',
        usertype: '0',
        viewtype: '0',
        agenttype: '0',
        creatorId: '26085',
        requestId: '503918',
        createTime: '2025-10-15 18:04:23',
        isbereject: '',
        creatorName: 'Developer 1',
        isprocessed: '',
        operateTime: ' ',
        preisremark: '0',
        receiveTime: '2025-10-15 18:04:23',
        requestName: 'ICSA BU Group Summary Report Submission Flow-Developer 1-2025-10-15',
        requestmark: 'ICSA2025372',
        takisremark: '',
        requestLevel: '0',
        currentNodeId: '657',
        lastOperatorId: '26085',
        currentNodeName: 'Upload and submit Report Outline',
        currentnodetype: '2',
        lastOperateTime: '2025-10-15 18:04:23',
        agentorbyagentid: '-1',
        lastOperatorName: 'Developer 1',
        userDepartmentId: '33861',
        userSubcompanyId: '280',
        workflowBaseInfo: {
          formId: '-330',
          workflowId: '111',
          workflowName: 'ICSA BU Group Summary Report Submission Flow',
          workflowTypeId: '47',
          workflowTypeName: 'GICRM - Internal Control Self-Assessment',
        },
        userDepartmentName: 'DCHBI',
        userSubcompanyName: 'Operation',
        creatorDepartmentId: '3255',
        creatorSubcompanyId: '262',
        creatorDepartmentName: 'Prof Svc-Low Code Platform',
        creatorSubcompanyName: 'Others Business',
      },
      {
        cid: '555073',
        nodeid: '657',
        status: 'Pending',
        userid: '19831',
        sysName: 'OA',
        isremark: '0',
        userName: 'shu yaojin',
        usertype: '0',
        viewtype: '0',
        agenttype: '0',
        creatorId: '26085',
        requestId: '503914',
        createTime: '2025-10-15 15:32:17',
        isbereject: '',
        creatorName: 'Developer 1',
        isprocessed: '',
        operateTime: ' ',
        preisremark: '0',
        receiveTime: '2025-10-15 15:32:17',
        requestName: 'ICSA BU Group Summary Report Submission Flow-Developer 1-2025-10-15',
        requestmark: 'ICSA2025371',
        takisremark: '',
        requestLevel: '0',
        currentNodeId: '657',
        lastOperatorId: '26085',
        currentNodeName: 'Upload and submit Report Outline',
        currentnodetype: '2',
        lastOperateTime: '2025-10-15 15:32:17',
        agentorbyagentid: '-1',
        lastOperatorName: 'Developer 1',
        userDepartmentId: '33861',
        userSubcompanyId: '280',
        workflowBaseInfo: {
          formId: '-330',
          workflowId: '111',
          workflowName: 'ICSA BU Group Summary Report Submission Flow',
          workflowTypeId: '47',
          workflowTypeName: 'GICRM - Internal Control Self-Assessment',
        },
        userDepartmentName: 'DCHBI',
        userSubcompanyName: 'Operation',
        creatorDepartmentId: '3255',
        creatorSubcompanyId: '262',
        creatorDepartmentName: 'Prof Svc-Low Code Platform',
        creatorSubcompanyName: 'Others Business',
      },
      {
        cid: '555050',
        nodeid: '657',
        status: 'Pending',
        userid: '19831',
        sysName: 'OA',
        isremark: '0',
        userName: 'shu yaojin',
        usertype: '0',
        viewtype: '0',
        agenttype: '0',
        creatorId: '26085',
        requestId: '503912',
        createTime: '2025-10-15 15:05:48',
        isbereject: '',
        creatorName: 'Developer 1',
        isprocessed: '',
        operateTime: ' ',
        preisremark: '0',
        receiveTime: '2025-10-15 15:05:48',
        requestName: 'ICSA BU Group Summary Report Submission Flow-Developer 1-2025-10-15',
        requestmark: 'ICSA2025370',
        takisremark: '',
        requestLevel: '0',
        currentNodeId: '657',
        lastOperatorId: '26085',
        currentNodeName: 'Upload and submit Report Outline',
        currentnodetype: '2',
        lastOperateTime: '2025-10-15 15:05:48',
        agentorbyagentid: '-1',
        lastOperatorName: 'Developer 1',
        userDepartmentId: '33861',
        userSubcompanyId: '280',
        workflowBaseInfo: {
          formId: '-330',
          workflowId: '111',
          workflowName: 'ICSA BU Group Summary Report Submission Flow',
          workflowTypeId: '47',
          workflowTypeName: 'GICRM - Internal Control Self-Assessment',
        },
        userDepartmentName: 'DCHBI',
        userSubcompanyName: 'Operation',
        creatorDepartmentId: '3255',
        creatorSubcompanyId: '262',
        creatorDepartmentName: 'Prof Svc-Low Code Platform',
        creatorSubcompanyName: 'Others Business',
      },
      {
        cid: '554523',
        nodeid: '653',
        status: '分叉起始点',
        userid: '19831',
        sysName: 'OA',
        isremark: '8',
        userName: 'shu yaojin',
        usertype: '0',
        viewtype: '0',
        agenttype: '0',
        creatorId: '26085',
        requestId: '503745',
        createTime: '2025-10-13 14:23:51',
        isbereject: '',
        creatorName: 'Developer 1',
        isprocessed: '',
        operateTime: ' ',
        preisremark: '8',
        receiveTime: '2025-10-13 14:23:51',
        requestName: 'ICSA Entity Submission Flow-Developer 1-2025-10-13',
        requestmark: 'ICSA20250432',
        takisremark: '',
        requestLevel: '0',
        currentNodeId: '653',
        lastOperatorId: '26085',
        currentNodeName: 'Fill-in Assessment',
        currentnodetype: '2',
        lastOperateTime: '2025-10-13 16:25:04',
        agentorbyagentid: '-1',
        lastOperatorName: 'Developer 1',
        userDepartmentId: '33861',
        userSubcompanyId: '280',
        workflowBaseInfo: {
          formId: '-323',
          workflowId: '107',
          workflowName: 'ICSA Entity Assessment & Quality Check Flow',
          workflowTypeId: '47',
          workflowTypeName: 'GICRM - Internal Control Self-Assessment',
        },
        userDepartmentName: 'DCHBI',
        userSubcompanyName: 'Operation',
        creatorDepartmentId: '3255',
        creatorSubcompanyId: '262',
        creatorDepartmentName: 'Prof Svc-Low Code Platform',
        creatorSubcompanyName: 'Others Business',
      },
      {
        cid: '554516',
        nodeid: '653',
        status: '分叉起始点',
        userid: '19831',
        sysName: 'OA',
        isremark: '8',
        userName: 'shu yaojin',
        usertype: '0',
        viewtype: '0',
        agenttype: '0',
        creatorId: '26085',
        requestId: '503744',
        createTime: '2025-10-13 14:20:22',
        isbereject: '',
        creatorName: 'Developer 1',
        isprocessed: '',
        operateTime: ' ',
        preisremark: '8',
        receiveTime: '2025-10-13 14:20:22',
        requestName: 'ICSA Entity Assessment & Quality Check Flow-Developer 1-2025-10-13',
        requestmark: 'ICSA20250431',
        takisremark: '',
        requestLevel: '0',
        currentNodeId: '653',
        lastOperatorId: '26085',
        currentNodeName: 'Fill-in Assessment',
        currentnodetype: '2',
        lastOperateTime: '2025-10-13 14:20:22',
        agentorbyagentid: '-1',
        lastOperatorName: 'Developer 1',
        userDepartmentId: '33861',
        userSubcompanyId: '280',
        workflowBaseInfo: {
          formId: '-323',
          workflowId: '107',
          workflowName: 'ICSA Entity Assessment & Quality Check Flow',
          workflowTypeId: '47',
          workflowTypeName: 'GICRM - Internal Control Self-Assessment',
        },
        userDepartmentName: 'DCHBI',
        userSubcompanyName: 'Operation',
        creatorDepartmentId: '3255',
        creatorSubcompanyId: '262',
        creatorDepartmentName: 'Prof Svc-Low Code Platform',
        creatorSubcompanyName: 'Others Business',
      },
      {
        cid: '554506',
        nodeid: '657',
        status: 'Pending',
        userid: '19831',
        sysName: 'OA',
        isremark: '0',
        userName: 'shu yaojin',
        usertype: '0',
        viewtype: '0',
        agenttype: '0',
        creatorId: '26085',
        requestId: '503743',
        createTime: '2025-10-13 11:41:47',
        isbereject: '',
        creatorName: 'Developer 1',
        isprocessed: '',
        operateTime: ' ',
        preisremark: '0',
        receiveTime: '2025-10-13 11:41:47',
        requestName: 'ICSA BU Group Summary Report Submission Flow-Developer 1-2025-10-13',
        requestmark: 'ICSA2025369',
        takisremark: '',
        requestLevel: '0',
        currentNodeId: '657',
        lastOperatorId: '26085',
        currentNodeName: 'Upload and submit Report Outline',
        currentnodetype: '2',
        lastOperateTime: '2025-10-13 11:41:47',
        agentorbyagentid: '-1',
        lastOperatorName: 'Developer 1',
        userDepartmentId: '33861',
        userSubcompanyId: '280',
        workflowBaseInfo: {
          formId: '-330',
          workflowId: '111',
          workflowName: 'ICSA BU Group Summary Report Submission Flow',
          workflowTypeId: '47',
          workflowTypeName: 'GICRM - Internal Control Self-Assessment',
        },
        userDepartmentName: 'DCHBI',
        userSubcompanyName: 'Operation',
        creatorDepartmentId: '3255',
        creatorSubcompanyId: '262',
        creatorDepartmentName: 'Prof Svc-Low Code Platform',
        creatorSubcompanyName: 'Others Business',
      },
    ]
  }
  try {
    const body: Record<string, any> = await readBody<Record<string, any>>(event).catch(() => ({}))
    const notificationApiPrefix = '/api/r/internal'
    const response = await $fetch.raw<Record<string, any>>(`${config.public.apiBase}${notificationApiPrefix}/ecology_oa/workflow_approval`, {
      method: 'POST',
      headers: getForwardHeaders(event),
      body: {
        pageNo: body.pageNo ?? body.pageNum ?? 1,
        pageSize: 10,
        otherParams: { is_handled: false },
      },
    })

    forwardSetCookieHeaders(event, response)

    return {
      success: true,
      data: response._data,
    }
  }
  catch (error: any) {
    console.error('Mark notification as read API error:', error)
  }
})
