export default defineEventHandler(async () => {

    return {
        data: [
                {
        "agentorbyagentid": "-1",
        "agenttype": "0",
        "cid": "619297",
        "createTime": "2026-04-13 16:07:40",
        "creatorDepartmentId": "33861",
        "creatorDepartmentName": "DCHBI",
        "creatorId": "24870",
        "creatorName": "mao yungui",
        "creatorSubcompanyId": "280",
        "creatorSubcompanyName": "Operation",
        "currentNodeId": "1396",
        "currentNodeName": "L1A",
        "currentnodetype": "1",
        "isbereject": "",
        "isprocessed": "",
        "isremark": "0",
        "lastOperateTime": "2026-04-13 16:09:39",
        "lastOperatorId": "24870",
        "lastOperatorName": "mao yungui",
        "nodeid": "1396",
        "operateTime": " ",
        "preisremark": "0",
        "receiveTime": "2026-04-13 16:07:45",
        "requestId": "799185",
        "requestLevel": "0",
        "requestName": "TestCosignOrConcurrent-mao yungui-2026-04-13",
        "requestmark": "TESTA00014",
        "status": "分叉中间点",
        "sysName": "OA",
        "takisremark": "",
        "userDepartmentId": "3255",
        "userDepartmentName": "Prof Svc-Low Code Platform",
        "userName": "Developer 1",
        "userSubcompanyId": "262",
        "userSubcompanyName": "Others Business",
        "userid": "26085",
        "usertype": "0",
        "viewtype": "0",
        "workflowBaseInfo": {
            "formId": "-630",
            "workflowId": "200",
            "workflowName": "TestCosignOrConcurrent",
            "workflowTypeId": "56",
            "workflowTypeName": "通用流程"
        }
    },
    {
        "agentorbyagentid": "-1",
        "agenttype": "0",
        "cid": "614949",
        "createTime": "2026-04-01 16:41:15",
        "creatorDepartmentId": "3255",
        "creatorDepartmentName": "Prof Svc-Low Code Platform",
        "creatorId": "23787",
        "creatorName": "Chan Chun Hong Felix",
        "creatorSubcompanyId": "262",
        "creatorSubcompanyName": "Others Business",
        "currentNodeId": "1396",
        "currentNodeName": "L1A",
        "currentnodetype": "1",
        "isbereject": "",
        "isprocessed": "",
        "isremark": "0",
        "lastOperateTime": "2026-04-01 17:28:27",
        "lastOperatorId": "26085",
        "lastOperatorName": "Developer 1",
        "nodeid": "1396",
        "operateTime": "2026-04-01 17:27:29",
        "preisremark": "0",
        "receiveTime": "2026-04-01 16:41:17",
        "requestId": "794871",
        "requestLevel": "0",
        "requestName": "TestCosignOrConcurrent-Chan Chun Hong Felix-2026-04-01",
        "requestmark": "TESTA00009",
        "status": "分叉中间点",
        "sysName": "OA",
        "takisremark": "",
        "userDepartmentId": "3255",
        "userDepartmentName": "Prof Svc-Low Code Platform",
        "userName": "Developer 1",
        "userSubcompanyId": "262",
        "userSubcompanyName": "Others Business",
        "userid": "26085",
        "usertype": "0",
        "viewtype": "-2",
        "workflowBaseInfo": {
            "formId": "-630",
            "workflowId": "200",
            "workflowName": "TestCosignOrConcurrent",
            "workflowTypeId": "56",
            "workflowTypeName": "通用流程"
        }
    },
    {
        "agentorbyagentid": "-1",
        "agenttype": "0",
        "cid": "614942",
        "createTime": "2026-03-31 18:03:03",
        "creatorDepartmentId": "3255",
        "creatorDepartmentName": "Prof Svc-Low Code Platform",
        "creatorId": "26085",
        "creatorName": "Developer 1",
        "creatorSubcompanyId": "262",
        "creatorSubcompanyName": "Others Business",
        "currentNodeId": "1387",
        "currentNodeName": "L2B",
        "currentnodetype": "1",
        "isbereject": "",
        "isprocessed": "",
        "isremark": "0",
        "lastOperateTime": "2026-04-01 12:32:45",
        "lastOperatorId": "0",
        "lastOperatorName": "",
        "nodeid": "1387",
        "operateTime": "2026-04-10 12:12:38",
        "preisremark": "0",
        "receiveTime": "2026-04-01 12:32:45",
        "requestId": "792795",
        "requestLevel": "0",
        "requestName": "TestCosignOrConcurrent-Developer 1-2026-03-31",
        "requestmark": "TESTA00007",
        "status": "出口12",
        "sysName": "OA",
        "takisremark": "",
        "userDepartmentId": "3255",
        "userDepartmentName": "Prof Svc-Low Code Platform",
        "userName": "Developer 1",
        "userSubcompanyId": "262",
        "userSubcompanyName": "Others Business",
        "userid": "26085",
        "usertype": "0",
        "viewtype": "-2",
        "workflowBaseInfo": {
            "formId": "-630",
            "workflowId": "200",
            "workflowName": "TestCosignOrConcurrent",
            "workflowTypeId": "56",
            "workflowTypeName": "通用流程"
        }
    },
    {
        "agentorbyagentid": "-1",
        "agenttype": "0",
        "cid": "614484",
        "createTime": "2026-03-31 18:07:18",
        "creatorDepartmentId": "3255",
        "creatorDepartmentName": "Prof Svc-Low Code Platform",
        "creatorId": "26085",
        "creatorName": "Developer 1",
        "creatorSubcompanyId": "262",
        "creatorSubcompanyName": "Others Business",
        "currentNodeId": "1396",
        "currentNodeName": "L1A",
        "currentnodetype": "1",
        "isbereject": "",
        "isprocessed": "",
        "isremark": "0",
        "lastOperateTime": "2026-04-01 10:26:04",
        "lastOperatorId": "26085",
        "lastOperatorName": "Developer 1",
        "nodeid": "1396",
        "operateTime": "2026-03-31 18:15:57",
        "preisremark": "0",
        "receiveTime": "2026-03-31 18:07:19",
        "requestId": "792796",
        "requestLevel": "0",
        "requestName": "TestCosignOrConcurrent-Developer 1-2026-03-31",
        "requestmark": "TESTA00008",
        "status": "分叉中间点",
        "sysName": "OA",
        "takisremark": "",
        "userDepartmentId": "3255",
        "userDepartmentName": "Prof Svc-Low Code Platform",
        "userName": "Developer 1",
        "userSubcompanyId": "262",
        "userSubcompanyName": "Others Business",
        "userid": "26085",
        "usertype": "0",
        "viewtype": "-2",
        "workflowBaseInfo": {
            "formId": "-630",
            "workflowId": "200",
            "workflowName": "TestCosignOrConcurrent",
            "workflowTypeId": "56",
            "workflowTypeName": "通用流程"
        }
    },
    {
        "agentorbyagentid": "-1",
        "agenttype": "0",
        "cid": "614470",
        "createTime": "2026-03-31 18:02:10",
        "creatorDepartmentId": "3255",
        "creatorDepartmentName": "Prof Svc-Low Code Platform",
        "creatorId": "26085",
        "creatorName": "Developer 1",
        "creatorSubcompanyId": "262",
        "creatorSubcompanyName": "Others Business",
        "currentNodeId": "1396",
        "currentNodeName": "L1A",
        "currentnodetype": "1",
        "isbereject": "",
        "isprocessed": "",
        "isremark": "0",
        "lastOperateTime": "2026-03-31 18:02:14",
        "lastOperatorId": "0",
        "lastOperatorName": "",
        "nodeid": "1396",
        "operateTime": " ",
        "preisremark": "0",
        "receiveTime": "2026-03-31 18:02:14",
        "requestId": "792794",
        "requestLevel": "0",
        "requestName": "TestCosignOrConcurrent-Developer 1-2026-03-31",
        "requestmark": "TESTA00006",
        "status": "出口17",
        "sysName": "OA",
        "takisremark": "",
        "userDepartmentId": "3255",
        "userDepartmentName": "Prof Svc-Low Code Platform",
        "userName": "Developer 1",
        "userSubcompanyId": "262",
        "userSubcompanyName": "Others Business",
        "userid": "26085",
        "usertype": "0",
        "viewtype": "0",
        "workflowBaseInfo": {
            "formId": "-630",
            "workflowId": "200",
            "workflowName": "TestCosignOrConcurrent",
            "workflowTypeId": "56",
            "workflowTypeName": "通用流程"
        }
    },
    {
        "agentorbyagentid": "-1",
        "agenttype": "0",
        "cid": "614463",
        "createTime": "2026-03-31 18:01:15",
        "creatorDepartmentId": "3255",
        "creatorDepartmentName": "Prof Svc-Low Code Platform",
        "creatorId": "26085",
        "creatorName": "Developer 1",
        "creatorSubcompanyId": "262",
        "creatorSubcompanyName": "Others Business",
        "currentNodeId": "1396",
        "currentNodeName": "L1A",
        "currentnodetype": "1",
        "isbereject": "",
        "isprocessed": "",
        "isremark": "0",
        "lastOperateTime": "2026-03-31 18:01:19",
        "lastOperatorId": "0",
        "lastOperatorName": "",
        "nodeid": "1396",
        "operateTime": "2026-03-31 18:01:38",
        "preisremark": "0",
        "receiveTime": "2026-03-31 18:01:19",
        "requestId": "792793",
        "requestLevel": "0",
        "requestName": "TestCosignOrConcurrent-Developer 1-2026-03-31",
        "requestmark": "TESTA00005",
        "status": "出口17",
        "sysName": "OA",
        "takisremark": "",
        "userDepartmentId": "3255",
        "userDepartmentName": "Prof Svc-Low Code Platform",
        "userName": "Developer 1",
        "userSubcompanyId": "262",
        "userSubcompanyName": "Others Business",
        "userid": "26085",
        "usertype": "0",
        "viewtype": "-2",
        "workflowBaseInfo": {
            "formId": "-630",
            "workflowId": "200",
            "workflowName": "TestCosignOrConcurrent",
            "workflowTypeId": "56",
            "workflowTypeName": "通用流程"
        }
    },
    {
        "agentorbyagentid": "-1",
        "agenttype": "0",
        "cid": "614456",
        "createTime": "2026-03-31 17:57:22",
        "creatorDepartmentId": "3255",
        "creatorDepartmentName": "Prof Svc-Low Code Platform",
        "creatorId": "26085",
        "creatorName": "Developer 1",
        "creatorSubcompanyId": "262",
        "creatorSubcompanyName": "Others Business",
        "currentNodeId": "1387",
        "currentNodeName": "L2B",
        "currentnodetype": "1",
        "isbereject": "",
        "isprocessed": "",
        "isremark": "0",
        "lastOperateTime": "2026-03-31 17:59:24",
        "lastOperatorId": "0",
        "lastOperatorName": "",
        "nodeid": "1387",
        "operateTime": "2026-03-31 18:02:04",
        "preisremark": "0",
        "receiveTime": "2026-03-31 17:59:24",
        "requestId": "792792",
        "requestLevel": "0",
        "requestName": "TestCosignOrConcurrent-Developer 1-2026-03-31",
        "requestmark": "TESTA00004",
        "status": "出口12",
        "sysName": "OA",
        "takisremark": "",
        "userDepartmentId": "3255",
        "userDepartmentName": "Prof Svc-Low Code Platform",
        "userName": "Developer 1",
        "userSubcompanyId": "262",
        "userSubcompanyName": "Others Business",
        "userid": "26085",
        "usertype": "0",
        "viewtype": "-2",
        "workflowBaseInfo": {
            "formId": "-630",
            "workflowId": "200",
            "workflowName": "TestCosignOrConcurrent",
            "workflowTypeId": "56",
            "workflowTypeName": "通用流程"
        }
    },
    {
        "agentorbyagentid": "-1",
        "agenttype": "0",
        "cid": "614449",
        "createTime": "2026-03-31 16:28:13",
        "creatorDepartmentId": "3255",
        "creatorDepartmentName": "Prof Svc-Low Code Platform",
        "creatorId": "26085",
        "creatorName": "Developer 1",
        "creatorSubcompanyId": "262",
        "creatorSubcompanyName": "Others Business",
        "currentNodeId": "1387",
        "currentNodeName": "L2B",
        "currentnodetype": "1",
        "isbereject": "",
        "isprocessed": "",
        "isremark": "0",
        "lastOperateTime": "2026-04-01 10:30:41",
        "lastOperatorId": "26085",
        "lastOperatorName": "Developer 1",
        "nodeid": "1387",
        "operateTime": "2026-03-31 17:59:42",
        "preisremark": "0",
        "receiveTime": "2026-03-31 17:55:29",
        "requestId": "788791",
        "requestLevel": "0",
        "requestName": "TestCosignOrConcurrent-Developer 1-2026-03-31",
        "requestmark": "TESTA00003",
        "status": "出口12",
        "sysName": "OA",
        "takisremark": "",
        "userDepartmentId": "3255",
        "userDepartmentName": "Prof Svc-Low Code Platform",
        "userName": "Developer 1",
        "userSubcompanyId": "262",
        "userSubcompanyName": "Others Business",
        "userid": "26085",
        "usertype": "0",
        "viewtype": "-2",
        "workflowBaseInfo": {
            "formId": "-630",
            "workflowId": "200",
            "workflowName": "TestCosignOrConcurrent",
            "workflowTypeId": "56",
            "workflowTypeName": "通用流程"
        }
    },
    {
        "agentorbyagentid": "-1",
        "agenttype": "0",
        "cid": "614442",
        "createTime": "2026-03-31 16:24:06",
        "creatorDepartmentId": "3255",
        "creatorDepartmentName": "Prof Svc-Low Code Platform",
        "creatorId": "26085",
        "creatorName": "Developer 1",
        "creatorSubcompanyId": "262",
        "creatorSubcompanyName": "Others Business",
        "currentNodeId": "1385",
        "currentNodeName": "L1F",
        "currentnodetype": "1",
        "isbereject": "",
        "isprocessed": "",
        "isremark": "0",
        "lastOperateTime": "2026-03-31 16:24:36",
        "lastOperatorId": "26085",
        "lastOperatorName": "Developer 1",
        "nodeid": "1385",
        "operateTime": "2026-03-31 16:24:28",
        "preisremark": "0",
        "receiveTime": "2026-03-31 16:24:09",
        "requestId": "788790",
        "requestLevel": "0",
        "requestName": "TestCosignOrConcurrent-Developer 1-2026-03-31",
        "requestmark": "TESTA00002",
        "status": "分叉中间点",
        "sysName": "OA",
        "takisremark": "",
        "userDepartmentId": "3255",
        "userDepartmentName": "Prof Svc-Low Code Platform",
        "userName": "Developer 1",
        "userSubcompanyId": "262",
        "userSubcompanyName": "Others Business",
        "userid": "26085",
        "usertype": "0",
        "viewtype": "-2",
        "workflowBaseInfo": {
            "formId": "-630",
            "workflowId": "200",
            "workflowName": "TestCosignOrConcurrent",
            "workflowTypeId": "56",
            "workflowTypeName": "通用流程"
        }
    },
    {
        "agentorbyagentid": "-1",
        "agenttype": "0",
        "cid": "614437",
        "createTime": "2026-03-31 16:21:06",
        "creatorDepartmentId": "3255",
        "creatorDepartmentName": "Prof Svc-Low Code Platform",
        "creatorId": "26085",
        "creatorName": "Developer 1",
        "creatorSubcompanyId": "262",
        "creatorSubcompanyName": "Others Business",
        "currentNodeId": "1387",
        "currentNodeName": "L2B",
        "currentnodetype": "1",
        "isbereject": "",
        "isprocessed": "",
        "isremark": "0",
        "lastOperateTime": "2026-03-31 16:23:29",
        "lastOperatorId": "0",
        "lastOperatorName": "",
        "nodeid": "1387",
        "operateTime": "2026-03-31 16:23:49",
        "preisremark": "0",
        "receiveTime": "2026-03-31 16:23:29",
        "requestId": "788789",
        "requestLevel": "0",
        "requestName": "TestCosignOrConcurrent-Developer 1-2026-03-31",
        "requestmark": "TESTA00001",
        "status": "出口12",
        "sysName": "OA",
        "takisremark": "",
        "userDepartmentId": "3255",
        "userDepartmentName": "Prof Svc-Low Code Platform",
        "userName": "Developer 1",
        "userSubcompanyId": "262",
        "userSubcompanyName": "Others Business",
        "userid": "26085",
        "usertype": "0",
        "viewtype": "-2",
        "workflowBaseInfo": {
            "formId": "-630",
            "workflowId": "200",
            "workflowName": "TestCosignOrConcurrent",
            "workflowTypeId": "56",
            "workflowTypeName": "通用流程"
        }
    },
        ]
    }
})