export default defineEventHandler(async (event) => {
  const config = useRuntimeConfig()
  if (config.mockEnabled) {
    return [
      {
        cid: '322131',
        nodeid: '617',
        status: 'Issue to BU Champions',
        userid: '19831',
        sysName: 'OA',
        isremark: '0',
        userName: 'shu yaojin',
        usertype: '0',
        viewtype: '0',
        agenttype: '0',
        creatorId: '19831',
        requestId: '295320',
        createTime: '2025-03-05 16:50:28',
        isbereject: '',
        creatorName: 'shu yaojin',
        isprocessed: '',
        operateTime: ' ',
        preisremark: '0',
        receiveTime: '2025-03-06 09:20:27',
        requestName: 'ICSA Main Process-shu yaojin-2025-03-05',
        requestmark: '',
        takisremark: '',
        requestLevel: '0',
        currentNodeId: '617',
        lastOperatorId: '26085',
        currentNodeName: 'Confirm Entities by BU Champions',
        currentnodetype: '2',
        lastOperateTime: '2025-03-06 09:20:27',
        agentorbyagentid: '-1',
        lastOperatorName: 'Developer 1',
        userDepartmentId: '33861',
        userSubcompanyId: '280',
        workflowBaseInfo: {
          formId: '-322',
          workflowId: '106',
          workflowName: 'ICSA Main Process',
          workflowTypeId: '47',
          workflowTypeName: 'GICRM - Internal Control Self-Assessment',
        },
        userDepartmentName: 'DCHBI',
        userSubcompanyName: 'Operation',
        creatorDepartmentId: '33861',
        creatorSubcompanyId: '280',
        creatorDepartmentName: 'DCHBI',
        creatorSubcompanyName: 'Operation',
      },
      {
        cid: '322090',
        nodeid: '614',
        status: '',
        userid: '19831',
        sysName: 'OA',
        isremark: '0',
        userName: 'shu yaojin',
        usertype: '0',
        viewtype: '-2',
        agenttype: '0',
        creatorId: '19831',
        requestId: '295319',
        createTime: '2025-03-05 16:49:53',
        isbereject: '',
        creatorName: 'shu yaojin',
        isprocessed: '',
        operateTime: '2025-03-05 16:49:55',
        preisremark: '0',
        receiveTime: '2025-03-05 16:49:53',
        requestName: 'ICSA Main Process-shu yaojin-2025-03-05',
        requestmark: '',
        takisremark: '',
        requestLevel: '0',
        currentNodeId: '614',
        lastOperatorId: '19831',
        currentNodeName: 'Draft Assessment',
        currentnodetype: '0',
        lastOperateTime: '2025-03-05 16:49:53',
        agentorbyagentid: '-1',
        lastOperatorName: 'shu yaojin',
        userDepartmentId: '33861',
        userSubcompanyId: '280',
        workflowBaseInfo: {
          formId: '-322',
          workflowId: '106',
          workflowName: 'ICSA Main Process',
          workflowTypeId: '47',
          workflowTypeName: 'GICRM - Internal Control Self-Assessment',
        },
        userDepartmentName: 'DCHBI',
        userSubcompanyName: 'Operation',
        creatorDepartmentId: '33861',
        creatorSubcompanyId: '280',
        creatorDepartmentName: 'DCHBI',
        creatorSubcompanyName: 'Operation',
      },
      {
        cid: '322089',
        nodeid: '614',
        status: '',
        userid: '19831',
        sysName: 'OA',
        isremark: '0',
        userName: 'shu yaojin',
        usertype: '0',
        viewtype: '-2',
        agenttype: '0',
        creatorId: '19831',
        requestId: '295318',
        createTime: '2025-03-05 16:47:39',
        isbereject: '',
        creatorName: 'shu yaojin',
        isprocessed: '',
        operateTime: '2025-03-05 16:47:40',
        preisremark: '0',
        receiveTime: '2025-03-05 16:47:39',
        requestName: 'ICSA Main Process-shu yaojin-2025-03-05',
        requestmark: '',
        takisremark: '',
        requestLevel: '0',
        currentNodeId: '614',
        lastOperatorId: '19831',
        currentNodeName: 'Draft Assessment',
        currentnodetype: '0',
        lastOperateTime: '2025-03-05 16:47:39',
        agentorbyagentid: '-1',
        lastOperatorName: 'shu yaojin',
        userDepartmentId: '33861',
        userSubcompanyId: '280',
        workflowBaseInfo: {
          formId: '-322',
          workflowId: '106',
          workflowName: 'ICSA Main Process',
          workflowTypeId: '47',
          workflowTypeName: 'GICRM - Internal Control Self-Assessment',
        },
        userDepartmentName: 'DCHBI',
        userSubcompanyName: 'Operation',
        creatorDepartmentId: '33861',
        creatorSubcompanyId: '280',
        creatorDepartmentName: 'DCHBI',
        creatorSubcompanyName: 'Operation',
      },
    ]
  }
  try {
    const body: Record<string, any> = await readBody<Record<string, any>>(event).catch(() => ({}))
    const notificationApiPrefix = '/api/r/internal'
    const response = await $fetch.raw<Record<string, any>>(`${config.public.apiBase}${notificationApiPrefix}/ecology_oa/workflow_my_request`, {
      method: 'POST',
      headers: getForwardHeaders(event),
      body: {
        pageNo: body.pageNo ?? body.pageNum ?? 1,
        pageSize: 10,
        otherParams: { countOnly: false },
      },
    })

    forwardSetCookieHeaders(event, response)

    return {
      success: true,
      data: response._data,
    }
  }
  catch (error: any) {
    console.error('Mark notification as read API error:', error)
  }
})
