export default defineEventHandler(async () => {

    return {
        data: [
                {
        "agentorbyagentid": "-1",
        "agenttype": "0",
        "cid": "556645",
        "createTime": "2025-10-21 15:46:29",
        "creatorDepartmentId": "3255",
        "creatorDepartmentName": "Prof Svc-Low Code Platform",
        "creatorId": "26085",
        "creatorName": "Developer 1",
        "creatorSubcompanyId": "262",
        "creatorSubcompanyName": "Others Business",
        "currentNodeId": "807",
        "currentNodeName": "提交最终版本",
        "currentnodetype": "2",
        "isbereject": "",
        "isprocessed": "",
        "isremark": "0",
        "lastOperateTime": "2025-10-21 15:46:43",
        "lastOperatorId": "26085",
        "lastOperatorName": "Developer 1",
        "nodeid": "807",
        "operateTime": "2025-10-21 15:46:46",
        "preisremark": "0",
        "receiveTime": "2025-10-21 15:46:43",
        "requestId": "506898",
        "requestLevel": "0",
        "requestName": "集團合同許可與審核",
        "requestmark": "CCA20250095",
        "status": "提交最终版本",
        "sysName": "OA",
        "takisremark": "",
        "userDepartmentId": "3255",
        "userDepartmentName": "Prof Svc-Low Code Platform",
        "userName": "Developer 1",
        "userSubcompanyId": "262",
        "userSubcompanyName": "Others Business",
        "userid": "26085",
        "usertype": "0",
        "viewtype": "-2",
        "workflowBaseInfo": {
            "formId": "-332",
            "workflowId": "130",
            "workflowName": "集团合同许可与审核",
            "workflowTypeId": "37",
            "workflowTypeName": "GL - 合同管理"
        }
    },
    {
        "agentorbyagentid": "-1",
        "agenttype": "0",
        "cid": "555747",
        "createTime": "2025-10-17 16:31:06",
        "creatorDepartmentId": "3255",
        "creatorDepartmentName": "Prof Svc-Low Code Platform",
        "creatorId": "26085",
        "creatorName": "Developer 1",
        "creatorSubcompanyId": "262",
        "creatorSubcompanyName": "Others Business",
        "currentNodeId": "657",
        "currentNodeName": "Upload and submit Report Outline",
        "currentnodetype": "2",
        "isbereject": "",
        "isprocessed": "",
        "isremark": "0",
        "lastOperateTime": "2025-10-17 16:31:06",
        "lastOperatorId": "26085",
        "lastOperatorName": "Developer 1",
        "nodeid": "657",
        "operateTime": "2025-10-17 16:31:26",
        "preisremark": "0",
        "receiveTime": "2025-10-17 16:31:06",
        "requestId": "506594",
        "requestLevel": "0",
        "requestName": "ICSA BU Group Summary Report Submission Flow-Developer 1-2025-10-17",
        "requestmark": "ICSA2025375",
        "status": "Pending",
        "sysName": "OA",
        "takisremark": "",
        "userDepartmentId": "3255",
        "userDepartmentName": "Prof Svc-Low Code Platform",
        "userName": "Developer 1",
        "userSubcompanyId": "262",
        "userSubcompanyName": "Others Business",
        "userid": "26085",
        "usertype": "0",
        "viewtype": "-2",
        "workflowBaseInfo": {
            "formId": "-330",
            "workflowId": "111",
            "workflowName": "ICSA BU Group Summary Report Submission Flow",
            "workflowTypeId": "47",
            "workflowTypeName": "GICRM - Internal Control Self-Assessment"
        }
    },
    {
        "agentorbyagentid": "-1",
        "agenttype": "0",
        "cid": "555719",
        "createTime": "2025-10-17 16:20:37",
        "creatorDepartmentId": "3255",
        "creatorDepartmentName": "Prof Svc-Low Code Platform",
        "creatorId": "26085",
        "creatorName": "Developer 1",
        "creatorSubcompanyId": "262",
        "creatorSubcompanyName": "Others Business",
        "currentNodeId": "616",
        "currentNodeName": "Submit Assessment Request",
        "currentnodetype": "2",
        "isbereject": "",
        "isprocessed": "",
        "isremark": "0",
        "lastOperateTime": "2025-10-17 16:20:37",
        "lastOperatorId": "26085",
        "lastOperatorName": "Developer 1",
        "nodeid": "616",
        "operateTime": "2025-10-17 16:21:53",
        "preisremark": "0",
        "receiveTime": "2025-10-17 16:20:37",
        "requestId": "506592",
        "requestLevel": "0",
        "requestName": "ICSA Main Process-Developer 1-2025-10-17",
        "requestmark": "ICSA2025374",
        "status": "Review by GICRM",
        "sysName": "OA",
        "takisremark": "",
        "userDepartmentId": "3255",
        "userDepartmentName": "Prof Svc-Low Code Platform",
        "userName": "Developer 1",
        "userSubcompanyId": "262",
        "userSubcompanyName": "Others Business",
        "userid": "26085",
        "usertype": "0",
        "viewtype": "-2",
        "workflowBaseInfo": {
            "formId": "-322",
            "workflowId": "106",
            "workflowName": "ICSA Main Process",
            "workflowTypeId": "47",
            "workflowTypeName": "GICRM - Internal Control Self-Assessment"
        }
    },
    {
        "agentorbyagentid": "-1",
        "agenttype": "0",
        "cid": "555688",
        "createTime": "2025-10-17 15:24:41",
        "creatorDepartmentId": "3255",
        "creatorDepartmentName": "Prof Svc-Low Code Platform",
        "creatorId": "26085",
        "creatorName": "Developer 1",
        "creatorSubcompanyId": "262",
        "creatorSubcompanyName": "Others Business",
        "currentNodeId": "682",
        "currentNodeName": "Quality Check",
        "currentnodetype": "2",
        "isbereject": "",
        "isprocessed": "",
        "isremark": "0",
        "lastOperateTime": "2025-10-17 15:24:41",
        "lastOperatorId": "26085",
        "lastOperatorName": "Developer 1",
        "nodeid": "682",
        "operateTime": "2025-10-17 15:27:44",
        "preisremark": "0",
        "receiveTime": "2025-10-17 15:24:41",
        "requestId": "506590",
        "requestLevel": "0",
        "requestName": "ICSA Entity Assessment & Quality Check Flow-Developer 1-2025-10-17",
        "requestmark": "ICSA20250438",
        "status": "Generate QC",
        "sysName": "OA",
        "takisremark": "",
        "userDepartmentId": "3255",
        "userDepartmentName": "Prof Svc-Low Code Platform",
        "userName": "Developer 1",
        "userSubcompanyId": "262",
        "userSubcompanyName": "Others Business",
        "userid": "26085",
        "usertype": "0",
        "viewtype": "-2",
        "workflowBaseInfo": {
            "formId": "-323",
            "workflowId": "107",
            "workflowName": "ICSA Entity Assessment & Quality Check Flow",
            "workflowTypeId": "47",
            "workflowTypeName": "GICRM - Internal Control Self-Assessment"
        }
    },
    {
        "agentorbyagentid": "-1",
        "agenttype": "0",
        "cid": "555648",
        "createTime": "2025-10-17 14:40:27",
        "creatorDepartmentId": "3255",
        "creatorDepartmentName": "Prof Svc-Low Code Platform",
        "creatorId": "26085",
        "creatorName": "Developer 1",
        "creatorSubcompanyId": "262",
        "creatorSubcompanyName": "Others Business",
        "currentNodeId": "657",
        "currentNodeName": "Upload and submit Report Outline",
        "currentnodetype": "2",
        "isbereject": "",
        "isprocessed": "",
        "isremark": "0",
        "lastOperateTime": "2025-10-17 14:40:27",
        "lastOperatorId": "26085",
        "lastOperatorName": "Developer 1",
        "nodeid": "657",
        "operateTime": "2025-10-17 14:40:58",
        "preisremark": "0",
        "receiveTime": "2025-10-17 14:40:27",
        "requestId": "506587",
        "requestLevel": "0",
        "requestName": "ICSA BU Group Summary Report Submission Flow-Developer 1-2025-10-17",
        "requestmark": "ICSA2025373",
        "status": "Pending",
        "sysName": "OA",
        "takisremark": "",
        "userDepartmentId": "3255",
        "userDepartmentName": "Prof Svc-Low Code Platform",
        "userName": "Developer 1",
        "userSubcompanyId": "262",
        "userSubcompanyName": "Others Business",
        "userid": "26085",
        "usertype": "0",
        "viewtype": "-2",
        "workflowBaseInfo": {
            "formId": "-330",
            "workflowId": "111",
            "workflowName": "ICSA BU Group Summary Report Submission Flow",
            "workflowTypeId": "47",
            "workflowTypeName": "GICRM - Internal Control Self-Assessment"
        }
    },
    {
        "agentorbyagentid": "-1",
        "agenttype": "0",
        "cid": "555133",
        "createTime": "2025-10-15 18:04:23",
        "creatorDepartmentId": "3255",
        "creatorDepartmentName": "Prof Svc-Low Code Platform",
        "creatorId": "26085",
        "creatorName": "Developer 1",
        "creatorSubcompanyId": "262",
        "creatorSubcompanyName": "Others Business",
        "currentNodeId": "657",
        "currentNodeName": "Upload and submit Report Outline",
        "currentnodetype": "2",
        "isbereject": "",
        "isprocessed": "",
        "isremark": "0",
        "lastOperateTime": "2025-10-15 18:04:23",
        "lastOperatorId": "26085",
        "lastOperatorName": "Developer 1",
        "nodeid": "657",
        "operateTime": "2025-10-15 18:05:23",
        "preisremark": "0",
        "receiveTime": "2025-10-15 18:04:23",
        "requestId": "503918",
        "requestLevel": "0",
        "requestName": "ICSA BU Group Summary Report Submission Flow-Developer 1-2025-10-15",
        "requestmark": "ICSA2025372",
        "status": "Pending",
        "sysName": "OA",
        "takisremark": "",
        "userDepartmentId": "3255",
        "userDepartmentName": "Prof Svc-Low Code Platform",
        "userName": "Developer 1",
        "userSubcompanyId": "262",
        "userSubcompanyName": "Others Business",
        "userid": "26085",
        "usertype": "0",
        "viewtype": "-2",
        "workflowBaseInfo": {
            "formId": "-330",
            "workflowId": "111",
            "workflowName": "ICSA BU Group Summary Report Submission Flow",
            "workflowTypeId": "47",
            "workflowTypeName": "GICRM - Internal Control Self-Assessment"
        }
    },
    {
        "agentorbyagentid": "-1",
        "agenttype": "0",
        "cid": "555110",
        "createTime": "2025-10-15 17:22:13",
        "creatorDepartmentId": "3255",
        "creatorDepartmentName": "Prof Svc-Low Code Platform",
        "creatorId": "26085",
        "creatorName": "Developer 1",
        "creatorSubcompanyId": "262",
        "creatorSubcompanyName": "Others Business",
        "currentNodeId": "683",
        "currentNodeName": "QC - Entity Response",
        "currentnodetype": "2",
        "isbereject": "1",
        "isprocessed": "",
        "isremark": "0",
        "lastOperateTime": "2025-10-15 17:33:44",
        "lastOperatorId": "26085",
        "lastOperatorName": "Developer 1",
        "nodeid": "683",
        "operateTime": "2025-10-15 17:35:46",
        "preisremark": "0",
        "receiveTime": "2025-10-15 17:33:44",
        "requestId": "503916",
        "requestLevel": "0",
        "requestName": "ICSA Entity Assessment & Quality Check Flow-Developer 1-2025-10-15",
        "requestmark": "ICSA20250434",
        "status": "Return for Clarification",
        "sysName": "OA",
        "takisremark": "",
        "userDepartmentId": "3255",
        "userDepartmentName": "Prof Svc-Low Code Platform",
        "userName": "Developer 1",
        "userSubcompanyId": "262",
        "userSubcompanyName": "Others Business",
        "userid": "26085",
        "usertype": "0",
        "viewtype": "-2",
        "workflowBaseInfo": {
            "formId": "-323",
            "workflowId": "107",
            "workflowName": "ICSA Entity Assessment & Quality Check Flow",
            "workflowTypeId": "47",
            "workflowTypeName": "GICRM - Internal Control Self-Assessment"
        }
    },
    {
        "agentorbyagentid": "-1",
        "agenttype": "0",
        "cid": "555075",
        "createTime": "2025-10-15 15:32:17",
        "creatorDepartmentId": "3255",
        "creatorDepartmentName": "Prof Svc-Low Code Platform",
        "creatorId": "26085",
        "creatorName": "Developer 1",
        "creatorSubcompanyId": "262",
        "creatorSubcompanyName": "Others Business",
        "currentNodeId": "657",
        "currentNodeName": "Upload and submit Report Outline",
        "currentnodetype": "2",
        "isbereject": "",
        "isprocessed": "",
        "isremark": "0",
        "lastOperateTime": "2025-10-15 15:32:17",
        "lastOperatorId": "26085",
        "lastOperatorName": "Developer 1",
        "nodeid": "657",
        "operateTime": "2025-10-15 15:49:36",
        "preisremark": "0",
        "receiveTime": "2025-10-15 15:32:17",
        "requestId": "503914",
        "requestLevel": "0",
        "requestName": "ICSA BU Group Summary Report Submission Flow-Developer 1-2025-10-15",
        "requestmark": "ICSA2025371",
        "status": "Pending",
        "sysName": "OA",
        "takisremark": "",
        "userDepartmentId": "3255",
        "userDepartmentName": "Prof Svc-Low Code Platform",
        "userName": "Developer 1",
        "userSubcompanyId": "262",
        "userSubcompanyName": "Others Business",
        "userid": "26085",
        "usertype": "0",
        "viewtype": "-2",
        "workflowBaseInfo": {
            "formId": "-330",
            "workflowId": "111",
            "workflowName": "ICSA BU Group Summary Report Submission Flow",
            "workflowTypeId": "47",
            "workflowTypeName": "GICRM - Internal Control Self-Assessment"
        }
    },
    {
        "agentorbyagentid": "-1",
        "agenttype": "0",
        "cid": "555052",
        "createTime": "2025-10-15 15:05:48",
        "creatorDepartmentId": "3255",
        "creatorDepartmentName": "Prof Svc-Low Code Platform",
        "creatorId": "26085",
        "creatorName": "Developer 1",
        "creatorSubcompanyId": "262",
        "creatorSubcompanyName": "Others Business",
        "currentNodeId": "657",
        "currentNodeName": "Upload and submit Report Outline",
        "currentnodetype": "2",
        "isbereject": "",
        "isprocessed": "",
        "isremark": "0",
        "lastOperateTime": "2025-10-15 15:05:48",
        "lastOperatorId": "26085",
        "lastOperatorName": "Developer 1",
        "nodeid": "657",
        "operateTime": "2025-10-15 15:08:44",
        "preisremark": "0",
        "receiveTime": "2025-10-15 15:05:48",
        "requestId": "503912",
        "requestLevel": "0",
        "requestName": "ICSA BU Group Summary Report Submission Flow-Developer 1-2025-10-15",
        "requestmark": "ICSA2025370",
        "status": "Pending",
        "sysName": "OA",
        "takisremark": "",
        "userDepartmentId": "3255",
        "userDepartmentName": "Prof Svc-Low Code Platform",
        "userName": "Developer 1",
        "userSubcompanyId": "262",
        "userSubcompanyName": "Others Business",
        "userid": "26085",
        "usertype": "0",
        "viewtype": "-2",
        "workflowBaseInfo": {
            "formId": "-330",
            "workflowId": "111",
            "workflowName": "ICSA BU Group Summary Report Submission Flow",
            "workflowTypeId": "47",
            "workflowTypeName": "GICRM - Internal Control Self-Assessment"
        }
    },
    {
        "agentorbyagentid": "-1",
        "agenttype": "0",
        "cid": "554519",
        "createTime": "2025-10-13 14:23:51",
        "creatorDepartmentId": "3255",
        "creatorDepartmentName": "Prof Svc-Low Code Platform",
        "creatorId": "26085",
        "creatorName": "Developer 1",
        "creatorSubcompanyId": "262",
        "creatorSubcompanyName": "Others Business",
        "currentNodeId": "653",
        "currentNodeName": "Fill-in Assessment",
        "currentnodetype": "2",
        "isbereject": "",
        "isprocessed": "",
        "isremark": "0",
        "lastOperateTime": "2025-10-13 16:25:04",
        "lastOperatorId": "26085",
        "lastOperatorName": "Developer 1",
        "nodeid": "653",
        "operateTime": "2025-10-13 14:25:36",
        "preisremark": "0",
        "receiveTime": "2025-10-13 14:23:51",
        "requestId": "503745",
        "requestLevel": "0",
        "requestName": "ICSA Entity Submission Flow-Developer 1-2025-10-13",
        "requestmark": "ICSA20250432",
        "status": "分叉起始点",
        "sysName": "OA",
        "takisremark": "",
        "userDepartmentId": "3255",
        "userDepartmentName": "Prof Svc-Low Code Platform",
        "userName": "Developer 1",
        "userSubcompanyId": "262",
        "userSubcompanyName": "Others Business",
        "userid": "26085",
        "usertype": "0",
        "viewtype": "-2",
        "workflowBaseInfo": {
            "formId": "-323",
            "workflowId": "107",
            "workflowName": "ICSA Entity Assessment & Quality Check Flow",
            "workflowTypeId": "47",
            "workflowTypeName": "GICRM - Internal Control Self-Assessment"
        }
    },
        ]
    }
})