import type { TioTopic } from '~/types/tiopsServices'

const mockServices: TioTopic[] = [
  {
    category_en: 'IT and System Support',
    category_sc: 'IT与系统支持',
    category_tc: 'IT與系統支持',
    icon_x86: 'server',
    items: [
      {
        name_en: 'Report an Issue',
        name_sc: '报告问题',
        name_tc: '報告問題',
        icon_x86: 'bug',
        desktop_url: 'https://dch.service-now.com/sp?id=sc_cat_item&sys_id=3f1dd0320a0a0b99000a53f7604a2ef9&sysparm_category=af9c65c9db7951908e9ddf0bd3961975',
        mobile_url: 'https://dch.service-now.com/sp?id=sc_cat_item&sys_id=3f1dd0320a0a0b99000a53f7604a2ef9&sysparm_category=af9c65c9db7951908e9ddf0bd3961975',
        region: ['hk'],
        service_type: 'workflow',
        process_group: ['Staff Onboarding', 'Staff Offboarding'],
      },
      {
        name_en: 'Open a Service Request',
        name_sc: '一般 IT 服务和应用程式请求',
        name_tc: '一般 IT 服務和應用程式請求',
        icon_x86: 'service',
        desktop_url: 'https://dch.service-now.com/sp?id=sc_cat_item&sys_id=ea6aef15db3d91908e9ddf0bd3961922&sysparm_category=22c62651db7991908e9ddf0bd39619d2',
        mobile_url: 'https://dch.service-now.com/sp?id=sc_cat_item&sys_id=ea6aef15db3d91908e9ddf0bd3961922&sysparm_category=22c62651db7991908e9ddf0bd39619d2',
        region: ['hk'],
        service_type: 'workflow',
        process_group: ['Staff Onboarding', 'Staff Offboarding'],
      },
    ],
  },
  {
    category_en: 'Company and Administration',
    category_sc: '公司与行政',
    category_tc: '公司與行政',
    icon_x86: 'building',
    items: [
      {
        name_en: 'Intranet',
        name_sc: '企业内网',
        name_tc: '企業內聯網',
        icon_x86: 'portal',
        desktop_url: 'http://intranet.dch.com.hk/',
        mobile_url: 'http://intranet.dch.com.hk/',
        region: ['hk'],
        service_type: 'portal',
        process_group: ['Staff Onboarding'],
      },
      {
        name_en: 'Policy Documents',
        name_sc: '政策文件',
        name_tc: '政策文件',
        icon_x86: 'policy',
        desktop_url: 'https://oa-uat.dchbi.app/desktop/company-documents',
        mobile_url: 'https://oa-uat.dchbi.app/desktop/company-documents',
        region: ['hk', 'cn', 'sea'],
        service_type: 'knowledge',
        process_group: ['Staff Onboarding'],
      },
    ],
  },
  {
    category_en: 'Learning and Policy',
    category_sc: '学习与政策',
    category_tc: '學習與政策',
    icon_x86: 'book',
    items: [
      {
        name_en: 'Learning Management System',
        name_sc: '学习管理系统',
        name_tc: '學習管理系統',
        icon_x86: 'learning',
        desktop_url: '',
        mobile_url: '',
        region: ['hk'],
        service_type: 'application',
        process_group: ['Staff Onboarding'],
      },
    ],
  },
  {
    category_en: 'Contracts and Compliance',
    category_sc: '合同与合规',
    category_tc: '合同與合規',
    icon_x86: 'shield',
    items: [
      {
        name_en: 'Contracts Approval Submission',
        name_sc: '合约审批提交',
        name_tc: '合約審批提交',
        icon_x86: 'contract',
        desktop_url: 'https://platform-uat.dchbi.app/spa/workflow/static4form/index.html#/main/workflow/req?iscreate=1&workflowid=213',
        mobile_url: 'https://platform-uat.dchbi.app/spa/workflow/static4form/index.html#/main/workflow/req?iscreate=1&workflowid=213',
        region: ['hk'],
        service_type: 'workflow',
        process_group: ['Contract Clearance'],
      },
      {
        name_en: 'Contract List',
        name_sc: '合同清单',
        name_tc: '合約清單',
        icon_x86: 'list',
        desktop_url: 'https://platform-uat.dchbi.app/spa/cube/index.html#/main/cube/search?customid=542',
        mobile_url: 'https://platform-uat.dchbi.app/wui/cas-entrance.jsp?path=https://platform-uat.dchbi.app/mobilemode/mobile/view.html?appHomepageId=1',
        region: ['hk'],
        service_type: 'record',
        process_group: ['Contract Clearance'],
      },
      {
        name_en: 'Policies and Guidelines',
        name_sc: '政策及指引',
        name_tc: '政策及指引',
        icon_x86: 'guideline',
        desktop_url: '',
        mobile_url: '',
        region: ['hk'],
        service_type: 'knowledge',
        process_group: ['Contract Clearance'],
      },
      {
        name_en: 'Contract Templates &Playbooks',
        name_sc: '合约范本及指引',
        name_tc: '合約範本及指引',
        icon_x86: 'reference',
        desktop_url: '',
        mobile_url: '',
        region: ['hk'],
        service_type: 'knowledge',
        process_group: ['Contract Clearance'],
      },
    ],
  },
  {
    category_en: 'Employee and HR',
    category_sc: '员工与人事',
    category_tc: '員工與人事',
    icon_x86: 'people',
    items: [
      {
        name_en: 'Leave Management',
        name_sc: '请假管理',
        name_tc: '請假管理',
        icon_x86: 'calendar',
        desktop_url: '',
        mobile_url: '',
        region: ['hk', 'sea'],
        service_type: 'workflow',
        process_group: [],
      },
      {
        name_en: 'Payroll Management',
        name_sc: '薪酬管理',
        name_tc: '薪酬管理',
        icon_x86: 'money',
        desktop_url: '',
        mobile_url: '',
        region: ['hk', 'sea'],
        service_type: 'workflow',
        process_group: [],
      },
      {
        name_en: 'Appraisal Management',
        name_sc: '绩效考核管理',
        name_tc: '績效評核管理',
        icon_x86: 'chart',
        desktop_url: '',
        mobile_url: '',
        region: ['hk', 'sea'],
        service_type: 'workflow',
        process_group: ['Staff Offboarding'],
      },
    ],
  },
  {
    category_en: 'Finance and Reimbursement',
    category_sc: '财务与报销',
    category_tc: '財務與報銷',
    icon_x86: 'wallet',
    items: [
      {
        name_en: 'Travel Request',
        name_sc: '差旅申请',
        name_tc: '差旅申請',
        icon_x86: 'travel',
        desktop_url: '',
        mobile_url: '',
        region: ['hk', 'sea'],
        service_type: 'workflow',
        process_group: ['Business Trip Reimbursement'],
      },
      {
        name_en: 'Claim Request',
        name_sc: '报销申请',
        name_tc: '報銷申請',
        icon_x86: 'receipt',
        desktop_url: '',
        mobile_url: '',
        region: ['hk', 'sea'],
        service_type: 'workflow',
        process_group: ['Business Trip Reimbursement'],
      },
      {
        name_en: 'Entertainment Request',
        name_sc: '客户招待申请',
        name_tc: '客戶招待申請',
        icon_x86: 'coffee',
        desktop_url: '',
        mobile_url: '',
        region: ['hk', 'sea'],
        service_type: 'workflow',
        process_group: ['Business Trip Reimbursement'],
      },
    ],
  },
  {
    category_en: 'Projects and Assets',
    category_sc: '项目与资产',
    category_tc: '項目與資產',
    icon_x86: 'rocket',
    items: [],
  },
  {
    category_en: 'Reports and Data',
    category_sc: '报表与数据',
    category_tc: '報表與數據',
    icon_x86: 'report',
    items: [],
  },
]

export default defineEventHandler(() => {
  const config = useRuntimeConfig()

  if (config.mockEnabled) {
    return mockServices
  }

  return []
})
