export default defineEventHandler(async () => {
  // 这里直接返回模拟数据，实际可以调用 Windmill API 获取新闻列表
  return {
    userRight: true,
    xml: '<?xml version="1.0" encoding="UTF-8"?><mxGraphModel grid="1" gridSize="10" guides="1" tooltips="1" connect="1" arrows="1" fold="1" page="1" pageScale="1" pageWidth="1430" pageHeight="516" background="#ffffff"><root><mxCell id="0" vertex="1"/><mxCell id="1" vertex="1" parent="0"/><mxCell edge="1" linkId="1739" id="link_1739" parent="1" value="base64_5Ye65Y+jMw==" source="node_1391" target="node_1386" isreject="0" exitInfo="" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;exitX=1;exitY=0.35;entryX=0;entryY=0.5;jettySize=auto;orthogonalLoop=1;"><mxGeometry as="geometry" relative="1"/></mxCell><mxCell edge="1" linkId="1740" id="link_1740" parent="1" value="base64_5Ye65Y+jNA==" source="node_1391" target="node_1385" isreject="0" exitInfo="" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;exitX=1;exitY=0.44999999999999996;entryX=0;entryY=0.5;jettySize=auto;orthogonalLoop=1;"><mxGeometry as="geometry" relative="1"/></mxCell><mxCell edge="1" linkId="1743" id="link_1743" parent="1" value="base64_5Ye65Y+jNQ==" source="node_1386" target="node_1384" isreject="0" exitInfo="" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;exitX=1;exitY=0.5;entryX=0;entryY=0.35;jettySize=auto;orthogonalLoop=1;"><mxGeometry as="geometry" relative="1"/></mxCell><mxCell edge="1" linkId="1742" id="link_1742" parent="1" value="base64_5Ye65Y+jNg==" source="node_1385" target="node_1384" isreject="0" exitInfo="" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;exitX=1;exitY=0.5;entryX=0;entryY=0.44999999999999996;jettySize=auto;orthogonalLoop=1;"><mxGeometry as="geometry" relative="1"/></mxCell><mxCell edge="1" linkId="1744" id="link_1744" parent="1" value="base64_5Ye65Y+jOA==" source="node_1387" target="node_1389" isreject="0" exitInfo="" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;exitX=1;exitY=0.5;entryX=0;entryY=0.45;jettySize=auto;orthogonalLoop=1;"><mxGeometry as="geometry" relative="1"/></mxCell><mxCell edge="1" linkId="1746" id="link_1746" parent="1" value="base64_5Ye65Y+jOQ==" source="node_1389" target="node_1383" isreject="0" exitInfo="" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;exitX=1;exitY=0.5;entryX=0;entryY=0.5;jettySize=auto;orthogonalLoop=1;"><mxGeometry as="geometry" relative="1"/></mxCell><mxCell edge="1" linkId="1745" id="link_1745" parent="1" value="base64_5Ye65Y+jMTA=" source="node_1388" target="node_1389" isreject="0" exitInfo="" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;exitX=1;exitY=0.5;entryX=0;entryY=0.55;jettySize=auto;orthogonalLoop=1;"><mxGeometry as="geometry" relative="1"/></mxCell><mxCell edge="1" linkId="1749" id="link_1749" parent="1" value="base64_5Ye65Y+jMTI=" source="node_1384" target="node_1387" isreject="0" exitInfo="" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;exitX=1;exitY=0.45;entryX=0;entryY=0.5;jettySize=auto;orthogonalLoop=1;"><mxGeometry as="geometry" relative="1"/></mxCell><mxCell edge="1" linkId="1750" id="link_1750" parent="1" value="base64_5Ye65Y+jMTM=" source="node_1384" target="node_1388" isreject="0" exitInfo="" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;exitX=1;exitY=0.55;entryX=0;entryY=0.5;jettySize=auto;orthogonalLoop=1;"><mxGeometry as="geometry" relative="1"/></mxCell><mxCell edge="1" linkId="1751" id="link_1751" parent="1" value="base64_5Ye65Y+jMTQ=" source="node_1382" target="node_1391" isreject="0" exitInfo="" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;exitX=1;exitY=0.5;entryX=0;entryY=0.5;jettySize=auto;orthogonalLoop=1;"><mxGeometry as="geometry" relative="1"/></mxCell><mxCell edge="1" linkId="1754" id="link_1754" parent="1" value="base64_5Ye65Y+jMTU=" source="node_1391" target="node_1395" isreject="0" exitInfo="" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;exitX=1;exitY=0.5499999999999999;entryX=0;entryY=0.5;jettySize=auto;orthogonalLoop=1;"><mxGeometry as="geometry" relative="1"/></mxCell><mxCell edge="1" linkId="1756" id="link_1756" parent="1" value="base64_5Ye65Y+jMTY=" source="node_1395" target="node_1384" isreject="0" exitInfo="" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;exitX=1;exitY=0.5;entryX=0;entryY=0.5499999999999999;jettySize=auto;orthogonalLoop=1;"><mxGeometry as="geometry" relative="1"/></mxCell><mxCell edge="1" linkId="1755" id="link_1755" parent="1" value="base64_5Ye65Y+jMTc=" source="node_1391" target="node_1396" isreject="0" exitInfo="" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;exitX=1;exitY=0.6499999999999999;entryX=0;entryY=0.5;jettySize=auto;orthogonalLoop=1;"><mxGeometry as="geometry" relative="1"/></mxCell><mxCell edge="1" linkId="1757" id="link_1757" parent="1" value="base64_5Ye65Y+jMTg=" source="node_1396" target="node_1384" isreject="0" exitInfo="" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;exitX=1;exitY=0.5;entryX=0;entryY=0.6499999999999999;jettySize=auto;orthogonalLoop=1;"><mxGeometry as="geometry" relative="1"/></mxCell><mxCell id="node_1382" nodeId="1382" value="base64_5Yib5bu6MQ==" vertex="1" parent="1" nodeType="0" nodeAttriBute="0" style="ellipse;whiteSpace=wrap;html=1;resizable=0;icons={&quot;right&quot;:&quot;icon-workflow-ceshi&quot;};fillColor=#BFF3C3;strokeColor=#5ABD6B;"><mxGeometry x="50" y="95" width="93" height="93" as="geometry"/></mxCell><mxCell id="node_1383" nodeId="1383" value="base64_5b2S5qGjMg==" vertex="1" parent="1" nodeType="3" nodeAttriBute="0" style="ellipse;whiteSpace=wrap;html=1;icons={&quot;right&quot;:&quot;icon-workflow-guidang&quot;};fillColor=#BFF3C3;strokeColor=#5ABD6B;resizable=0;"><mxGeometry x="1230" y="98" width="93" height="93" as="geometry"/></mxCell><mxCell id="node_1384" nodeId="1384" value="base64_TDFBcHByb3ZlZA==" vertex="1" parent="1" nodeType="6" nodeAttriBute="5" proportMerge="100" style="shape=hexagon;perimeter=hexagonPerimeter2;rotatable=0;whiteSpace=wrap;html=1;fillColor=#BFF3C3;strokeColor=#5ABD6B;resizable=0;icons={&quot;left&quot;:&quot;icon-workflow-hebing&quot;,&quot;center&quot;:&quot;icon icon-robot icon-robotRelease-preparation&quot;};"><mxGeometry x="520" y="102" width="120" height="80" as="geometry"/></mxCell><mxCell id="node_1385" nodeId="1385" value="base64_TDFG" vertex="1" parent="1" nodeType="1" nodeAttriBute="0" style="rhombus;whiteSpace=wrap;html=1;fillColor=#BFF3C3;strokeColor=#5ABD6B;resizable=0;"><mxGeometry x="340" y="182" width="110" height="100" as="geometry"/></mxCell><mxCell id="node_1386" nodeId="1386" value="base64_TDFC" vertex="1" parent="1" nodeType="1" nodeAttriBute="0" style="rhombus;whiteSpace=wrap;html=1;fillColor=#BFF3C3;strokeColor=#5ABD6B;resizable=0;"><mxGeometry x="340" y="70" width="110" height="100" as="geometry"/></mxCell><mxCell id="node_1387" nodeId="1387" value="base64_TDJC" vertex="1" parent="1" nodeType="1" nodeAttriBute="0" style="rhombus;whiteSpace=wrap;html=1;fillColor=#BFF3C3;strokeColor=#5ABD6B;resizable=0;"><mxGeometry x="860" y="55" width="110" height="100" as="geometry"/></mxCell><mxCell id="node_1388" nodeId="1388" value="base64_TDJG" vertex="1" parent="1" nodeType="1" nodeAttriBute="0" style="rhombus;whiteSpace=wrap;html=1;fillColor=#BFF3C3;strokeColor=#5ABD6B;resizable=0;"><mxGeometry x="860" y="180" width="110" height="100" as="geometry"/></mxCell><mxCell id="node_1389" nodeId="1389" value="base64_TDJBcHByb3ZlZA==" vertex="1" parent="1" nodeType="6" nodeAttriBute="5" proportMerge="100" style="shape=hexagon;perimeter=hexagonPerimeter2;rotatable=0;whiteSpace=wrap;html=1;fillColor=#BFF3C3;strokeColor=#5ABD6B;resizable=0;icons={&quot;left&quot;:&quot;icon-workflow-hebing&quot;,&quot;center&quot;:&quot;icon icon-robot icon-robotRelease-preparation&quot;};"><mxGeometry x="1030" y="120" width="120" height="80" as="geometry"/></mxCell><mxCell id="node_1391" nodeId="1391" value="base64_TDE=" vertex="1" parent="1" nodeType="6" nodeAttriBute="1" style="shape=hexagon;perimeter=hexagonPerimeter2;whiteSpace=wrap;html=1;fixedSize=1;rotatable=0;icons={&quot;left&quot;:&quot;icon-workflow-fencha&quot;,&quot;center&quot;:&quot;icon icon-robot icon-robotRelease-preparation&quot;};fillColor=#BFF3C3;strokeColor=#5ABD6B;resizable=0;fontColor=#345e3a;"><mxGeometry x="180" y="109" width="120" height="80" as="geometry"/></mxCell><mxCell id="node_1395" nodeId="1395" value="base64_TDFD" vertex="1" parent="1" nodeType="1" nodeAttriBute="0" style="rhombus;whiteSpace=wrap;html=1;fillColor=#BFF3C3;strokeColor=#5ABD6B;resizable=0;"><mxGeometry x="340" y="310" width="110" height="100" as="geometry"/></mxCell><mxCell id="node_1396" nodeId="1396" value="base64_TDFB" vertex="1" parent="1" nodeType="1" nodeAttriBute="0" style="rhombus;whiteSpace=wrap;html=1;fillColor=#BFF3C3;strokeColor=#5ABD6B;resizable=0;"><mxGeometry x="340" y="450" width="110" height="100" as="geometry"/></mxCell></root></mxGraphModel>',
    isE9Save: true,
    processInfo: {
      canEdit: true,
      canView: true,
      createTime: '2026-04-01 16:41:15',
      creatorId: '23787',
      creatorName: 'Chan Chun Hong Felix',
      currentNodeId: '1385',
      currentNodeName: 'L1F',
      forwardButtonName: '转发',
      lastOperateTime: '2026-04-01 17:28:27',
      lastOperatorName: '',
      messageType: '0',
      mustInputRemark: false,
      needAffirmance: false,
      rejectButtonName: '',
      remark: '',
      requestId: '794871',
      requestLevel: '0',
      requestName: 'TestCosignOrConcurrent-Chan Chun Hong Felix-2026-04-01',
      status: '分叉中间点',
      subbackButtonName: '',
      submitButtonName: '批准',
      subnobackButtonName: '',
      workflowBaseInfo: {
        workflowId: '200',
        workflowName: 'TestCosignOrConcurrent',
        workflowTypeId: '56',
        workflowTypeName: '通用流程',
      },
      workflowMainTableInfo: {
        requestRecords: [
          {
            recordOrder: 0,
            workflowRequestTableFields: [
              {
                edit: true,
                fieldDBType: '',
                fieldFormName: 'requestname',
                fieldHtmlType: '1',
                fieldId: '-1',
                fieldName: 'requestname',
                fieldOrder: -1,
                fieldShowName: '标题',
                fieldShowValue: 'TestCosignOrConcurrent-Chan Chun Hong Felix-2026-04-01',
                fieldType: '',
                fieldValue: 'TestCosignOrConcurrent-Chan Chun Hong Felix-2026-04-01',
                filedHtmlShow: '<table style="width:100%;"><tr><td style="width:99%;white-space:normal;" align="left"><input type="text" name="requestname" id="requestname" value="TestCosignOrConcurrent-Chan Chun Hong Felix-2026-04-01" /></td><td><span id="requestname_ismandspan" class="ismand">!</span><input type="hidden" id="ismandfield" name="ismandfield" value="requestname"/></td></tr></table>',
                mand: true,
                view: true,
              },
              {
                edit: true,
                fieldDBType: '',
                fieldFormName: 'requestlevel',
                fieldHtmlType: '5',
                fieldId: '-2',
                fieldName: 'requestlevel',
                fieldOrder: -2,
                fieldShowName: '',
                fieldShowValue: '正常',
                fieldType: '',
                fieldValue: '0',
                filedHtmlShow: '<table style="width:100%;"><tr><td style="width:99%;white-space:normal;" align="left"><fieldset data-role="controlgroup"><input type="radio" name="requestlevel" id="requestlevel-0" value="0" checked /><label for="requestlevel-0">正常</label><input type="radio" name="requestlevel" id="requestlevel-1" value="1"  /><label for="requestlevel-1">重要</label><input type="radio" name="requestlevel" id="requestlevel-2" value="2"  /><label for="requestlevel-2">紧急</label></fieldset></td></tr></table>',
                mand: false,
                selectnames: [
                  '正常',
                  '重要',
                  '紧急',
                ],
                selectvalues: [
                  '0',
                  '1',
                  '2',
                ],
                view: true,
              },
              {
                edit: false,
                fieldDBType: '',
                fieldFormName: 'messageType',
                fieldHtmlType: '5',
                fieldId: '-3',
                fieldName: 'messageType',
                fieldOrder: -3,
                fieldShowName: '短信提醒',
                fieldShowValue: '不短信提醒',
                fieldType: '',
                fieldValue: '0',
                filedHtmlShow: '',
                mand: false,
                selectnames: [
                  '不短信提醒',
                  '离线短信提醒',
                  '在线短信提醒',
                ],
                selectvalues: [
                  '0',
                  '1',
                  '2',
                ],
                view: false,
              },
              {
                browserurl: '',
                edit: true,
                fieldDBType: 'varchar(16)',
                fieldFormName: 'field29988',
                fieldHtmlType: '1',
                fieldId: '29988',
                fieldName: 'caseno',
                fieldOrder: 0,
                fieldShowName: 'Case No',
                fieldShowValue: 'TESTA00009',
                fieldType: '1',
                fieldValue: 'TESTA00009',
                filedHtmlShow: '<table style="width:100%;"><tr><td style="width:99%;white-space:normal;" align="left"><input type="text" name="field29988" id="caseno" value="TESTA00009" onChange="checkLength(\'field29988\',16, \'Case No\', \'文本长度不能超过\', \'1个中文字符等于3个长度\');"/></td></tr></table>',
                mand: false,
                selectnames: [],
                selectvalues: [],
                view: true,
              },
              {
                browserurl: '',
                edit: true,
                fieldDBType: 'text',
                fieldFormName: 'field29995',
                fieldHtmlType: '6',
                fieldId: '29995',
                fieldName: 'file1',
                fieldOrder: 1,
                fieldShowName: 'File',
                fieldShowValue: '<span style=\'color:#ACA899\'>[该字段暂不支持]</span>',
                fieldType: '1',
                fieldValue: '',
                filedHtmlShow: '<span style=\'color:#ACA899\'>[该字段暂不支持]</span>',
                mand: false,
                selectnames: [],
                selectvalues: [],
                view: true,
              },
              {
                browserurl: '',
                edit: true,
                fieldDBType: 'text',
                fieldFormName: 'field29996',
                fieldHtmlType: '6',
                fieldId: '29996',
                fieldName: 'image',
                fieldOrder: 2,
                fieldShowName: 'Image',
                fieldShowValue: '<span style=\'text-decoration:underline;color:blue\' onclick="toURL(\'/news/download.do?fileid=47357&filename=portalglc (10).jpg\',false);" style="cursor:hand;">下载(396K)</span><br/><br/><span style=\'color:#ACA899\'>[该字段仅支持显示]</span>',
                fieldType: '2',
                fieldValue: '28676',
                filedHtmlShow: '<span style=\'text-decoration:underline;color:blue\' onclick="toURL(\'/news/download.do?fileid=47357&filename=portalglc (10).jpg\',false);" style="cursor:hand;">下载(396K)</span><br/><br/><span style=\'color:#ACA899\'>[该字段仅支持显示]</span>',
                mand: false,
                selectnames: [],
                selectvalues: [],
                view: true,
              },
            ],
          },
        ],
        tableDBName: 'formtable_main_630',
      },
      workflowRequestLogs: [
        {
          annexDocHtmls: '',
          id: '240147',
          nodeId: '1386',
          nodeName: 'L1B',
          operateDate: '2026-04-01',
          operateTime: '17:28:27',
          operateType: '批准',
          operatorDept: 'Prof Svc-Low Code Platform',
          operatorId: '26085',
          operatorName: 'Developer 1',
          receivedPersons: 'Wait For The Merger ,',
          remark: '<br><br><br><br><br><br>i am styled text',
          signDocHtmls: '',
          signWorkFlowHtmls: '',
        },
        {
          annexDocHtmls: '',
          id: '240144',
          nodeId: '1391',
          nodeName: 'L1',
          operateDate: '2026-04-01',
          operateTime: '16:41:17',
          operateType: '提交',
          operatorId: '0',
          operatorName: '系统',
          receivedPersons: 'Chan Chun Hong Felix,Developer 1',
          remark: 'Intelligent processing of process robot',
          signDocHtmls: '',
          signWorkFlowHtmls: '',
        },
        {
          annexDocHtmls: '',
          id: '240143',
          nodeId: '1382',
          nodeName: '创建1',
          operateDate: '2026-04-01',
          operateTime: '16:41:15',
          operateType: '提交',
          operatorDept: 'Prof Svc-Low Code Platform',
          operatorId: '23787',
          operatorName: 'Chan Chun Hong Felix',
          receivedPersons: '流程机器人',
          remark: '芟屏',
          signDocHtmls: '',
          signWorkFlowHtmls: '',
        },
      ],
    },
    formInfo: {
      hrmInfo: {
        belHrm: false,
      },
      secLevelInfo: {
        isOpenSec: false,
      },
      codeInfo: {
        isUse: true,
        codefields: [],
        fieldCode: '29988',
        hasHistoryCode: false,
      },
      maindata: {
        'field-1': {
          value: 'TestCosignOrConcurrent-Chan Chun Hong Felix-2026-04-01',
        },
        'field29988': {
          value: 'TESTA00009',
        },
        'field-2': {
          specialobj: [
            {
              isfc: '0',
              customname: '正常',
              id: '0',
              defaultname: '正常',
              showorder: '1',
            },
            {
              isfc: '0',
              customname: '重要',
              id: '1',
              defaultname: '重要',
              showorder: '2',
            },
            {
              isfc: '0',
              customname: '紧急',
              id: '2',
              defaultname: '紧急',
              showorder: '3',
            },
          ],
          value: '0',
        },
        'field-5': {
          value: '-1',
        },
        'field29995': {
          specialobj: {
            filedatas: [],
            showBatchLoad: false,
          },
          value: '',
        },
        'field29996': {
          specialobj: {
            filedatas: [
              {
                fileExtendName: 'jpg',
                isImg: true,
                imagefileid: '47357',
                filelink: '/spa/document/index2file.jsp?f_weaver_belongto_userid=26085&f_weaver_belongto_usertype=0&id=28676&imagefileId=47357&isFromAccessory=true&recordLog=1&isrequest=1&requestid=794871&desrequestid=0&authStr=dmlld0NoYWluPTc5NDg3MXxtYWluaWQ9Nzk0ODcxfA==&authSignatureStr=9d4a58f2a5c03606a35557ab726d6dea',
                uploaddate: '2026-04-01 17:12',
                showLoad: true,
                filesize: '388K',
                loadlink: '/weaver/weaver.file.FileDownload?fileid=ac6b7dc0dccfbe5b1d2e87cab99d0efe85f6569c70744684fa4eefadfbf17501ec126b557c1ea5be0c52762c6fe5501ce1b10c1f26484dbcd&download=1&requestid=794871&desrequestid=0&authStr=dmlld0NoYWluPTc5NDg3MXxtYWluaWQ9Nzk0ODcxfA==&authSignatureStr=9d4a58f2a5c03606a35557ab726d6dea&f_weaver_belongto_userid=26085&f_weaver_belongto_usertype=0&fromrequest=1',
                secretLevel: '4',
                isDoc: '1',
                versionId: 28591,
                filename: 'portalglc (10).jpg',
                fileidCode: 'afdb2b0942c8d7706f0baa9544b88901129b77c6961432eb887916112e4d3f604434958008c5fbd3849bfac335858bd12f0ce0e3c3ac16f21',
                secretLevelValidity: '',
                showDelete: true,
                imgSrc: '/weaver/weaver.file.FileDownload?fileid=ac6b7dc0dccfbe5b1d2e87cab99d0efe85f6569c70744684fa4eefadfbf17501ec126b557c1ea5be0c52762c6fe5501ce1b10c1f26484dbcd&requestid=794871&desrequestid=0&f_weaver_belongto_userid=26085&f_weaver_belongto_usertype=0&authStr=dmlld0NoYWluPTc5NDg3MXxtYWluaWQ9Nzk0ODcxfA==&authSignatureStr=9d4a58f2a5c03606a35557ab726d6dea',
                secretLevelValidityValue: '',
                fileid: '28676',
                username: 'Chan Chun Hong Felix',
              },
            ],
            showBatchLoad: false,
          },
          value: '28676',
        },
        'field-3': {
          value: '-1',
        },
        'field-9': {
          value: '0',
        },
      },
      odocInfo: {
        replaceTagGroup: {
          142: [],
          285: [],
        },
        docFlag: false,
      },
      secondAuthInfo: {},
      remindInfo: {
        process: '流程提醒',
        options: [],
        isShow: false,
      },
      tableInfo: {
        main: {
          fieldinfomap: {
            '29988': {
              detailtype: 1,
              existLayout: true,
              fielddbtype: 'varchar(16)',
              fieldgroupid: 0,
              fieldid: 29988,
              fieldlabel: 'Case No',
              fieldname: 'caseno',
              groupid: -1,
              htmltype: 1,
              isalonerow: false,
              isdetail: 0,
              isonlyshow: 0,
              length: 16,
              qfws: 0,
              textheight: 0,
              viewattr: 2,
            },
            '29995': {
              detailtype: 1,
              existLayout: true,
              fielddbtype: 'text',
              fieldgroupid: 0,
              fieldid: 29995,
              fieldlabel: 'File',
              fieldname: 'file1',
              fileattr: {
                catelogType: 0,
                docCategory: ',,3',
                fileSecFormat: 0,
                imgHeight: 0,
                imgWidth: 0,
                isautoupload: true,
                isresetname: true,
                isshowclerarall: false,
                issortable: true,
                limitType: '',
                maxUploadSize: 5,
                selectedCateLog: '0',
                showFilesize: true,
                showFullName: true,
                showSecLevel: true,
                showUploadTime: false,
                showUploader: false,
              },
              groupid: -1,
              htmltype: 6,
              isalonerow: false,
              isdetail: 0,
              isonlyshow: 0,
              length: 0,
              qfws: 0,
              textheight: 0,
              viewattr: 2,
            },
            '29996': {
              detailtype: 2,
              existLayout: true,
              fielddbtype: 'text',
              fieldgroupid: 0,
              fieldid: 29996,
              fieldlabel: 'Image',
              fieldname: 'image',
              fileattr: {
                catelogType: 0,
                docCategory: ',,3',
                fileSecFormat: 0,
                imgHeight: 100,
                imgWidth: 100,
                isautoupload: true,
                isresetname: true,
                isshowclerarall: false,
                issortable: true,
                limitType: 'jpg,gif,bmp,png,jpeg',
                maxUploadSize: 5,
                selectedCateLog: '0',
                showFilesize: true,
                showFullName: true,
                showSecLevel: true,
                showUploadTime: false,
                showUploader: false,
              },
              groupid: -1,
              htmltype: 6,
              isalonerow: false,
              isdetail: 0,
              isonlyshow: 0,
              length: 0,
              qfws: 0,
              textheight: 5,
              viewattr: 2,
            },
            '-1': {
              detailtype: 1,
              existLayout: true,
              fieldgroupid: 0,
              fieldid: -1,
              fieldlabel: '标题',
              groupid: 0,
              htmltype: 1,
              isalonerow: false,
              isdetail: 0,
              isonlyshow: 0,
              length: 0,
              qfws: 0,
              textheight: 0,
              viewattr: 3,
            },
            '-2': {
              detailtype: 1,
              existLayout: true,
              fieldgroupid: 0,
              fieldid: -2,
              fieldlabel: '紧急程度',
              groupid: 0,
              htmltype: 1,
              isalonerow: false,
              isdetail: 0,
              isonlyshow: 0,
              length: 0,
              qfws: 0,
              textheight: 0,
              viewattr: 2,
            },
            '-4': {
              detailtype: 1,
              existLayout: false,
              fieldgroupid: 0,
              fieldid: -4,
              fieldlabel: '签字意见',
              groupid: 0,
              htmltype: 1,
              isalonerow: false,
              isdetail: 0,
              isonlyshow: 0,
              length: 0,
              qfws: 0,
              textheight: 0,
              viewattr: 1,
            },
            '-9': {
              detailtype: 1,
              existLayout: true,
              fieldgroupid: 0,
              fieldid: -9,
              fieldlabel: '打印次数',
              groupid: 0,
              htmltype: 1,
              isalonerow: false,
              isdetail: 0,
              isonlyshow: 0,
              length: 0,
              qfws: 0,
              textheight: 0,
              viewattr: 1,
            },
            '-10': {
              detailtype: 1,
              existLayout: false,
              fieldgroupid: 0,
              fieldid: -10,
              fieldlabel: '密级',
              groupid: 0,
              htmltype: 1,
              isalonerow: false,
              isdetail: 0,
              isonlyshow: 0,
              length: 0,
              qfws: 0,
              textheight: 0,
              viewattr: 0,
            },
          },
          recordnum: 24,
          tablecolumn: 'caseno,file1,image,',
          tableindex: -1,
          tablename: 'formtable_main_630',
        },
      },
      params: {
        showDefaultLogList: '1',
        verifyRight: true,
        requestnamenew: 'TestCosignOrConcurrent-Chan Chun Hong Felix-2026-04-01',
        requestname: 'TestCosignOrConcurrent-Chan Chun Hong Felix-2026-04-01',
        beagenter: 0,
        belongTest: false,
        billIncludePage4mobile: '',
        issignmustinput: 0,
        selectNextFlowPattern: '-1',
        languageid: 7,
        openNodeCheck: false,
        flowDocFieldId: 0,
        showFreeWfSimpleCom: 0,
        showDefaultSign: '1',
        layouttype: 0,
        wfFormFieldChangeCfg: [],
        isFreeCustomeForm: 0,
        coworkid: 0,
        signatureAttributesStr: 'SXNCZUZvcndhcmRNb2RpZnk9MHxmb3JtaWQ9LTYzMHxyZXF1ZXN0bmFtZT1UZXN0Q29zaWduT3JDb25jdXJyZW50LUNoYW4gQ2h1biBIb25nIEZlbGl4LTIwMjYtMDQtMDF8dGFrZUJhY2s9MXxiZWFnZW50ZXI9MHxyZXF1ZXN0bGV2ZWw9MHxjb2FkaXNtb2RpZnk9MHxJc0JlRm9yd2FyZEFscmVhZHk9fElzQ2FuTW9kaWZ5PWZhbHNlfGNvYWRzaWdudHlwZT0yfGNyZWF0ZXJ0eXBlPTB8bGFzdE9wZXJhdGVEYXRlPTIwMjYtMDQtMDF8SXNXYWl0Rm9yd2FyZE9waW5pb249MHxwcmVpc3JlbWFyaz0wfG5vZGVpZD0xMzg1fHdvcmtmbG93aWQ9MjAwfGlzYmlsbD0xfElzQmVGb3J3YXJkUGVuZGluZz0wfGNhbnZpZXc9dHJ1ZXxpc2FnZW50PTB8aGVscGRvY2lkPTB8Y3VycmVudG5vZGVpZD0xMzk2fGlzUGVuZGluZ1JlbWFyaz10cnVlfElzQmVGb3J3YXJkU3VibWl0QWxyZWFkeT18SXNGcmVlTm9kZT18bGFzdE9wZXJhdGVUaW1lPTE3OjI4OjI3fElzSGFuZGxlRm9yd2FyZD0wfElzQmVGb3J3YXJkU3VibWl0Tm90YXJpZXM9fHJlcXVlc3RpZD03OTQ4NzF8Y3JlYXRlcj0yMzc4N3xJc0JlRm9yd2FyZFRvZG89fElzQmVGb3J3YXJkQ2FuU3VibWl0T3Bpbmlvbj10cnVlfHN0YXR1cz1+YH5gNyC31rLm1tC85LXjYH5gOCBNaWRkbGUgUG9pbnRgfmA5IEJpZnVyY2F0aW9uIGludGVybWVkaWF0ZSBwb2ludGB+YH58SXNDYW5TdWJtaXQ9dHJ1ZXxJc0ZyZWVXb3JrZmxvdz1mYWxzZXxjdXJyZW50bm9kZXR5cGU9MXxub2RldHlwZT0xfHJlcXVlc3RtYXJrPVRFU1RBMDAwMDl8bGFzdE9wZXJhdG9yPTI2MDg1fHdvcmtmbG93bmFtZT1UZXN0Q29zaWduT3JDb25jdXJyZW50fElzU3VibWl0Rm9yd2FyZD0wfGlzcmVtYXJrRm9yUk09MHxJc1BlbmRpbmdGb3J3YXJkPTF8Y29hZGlzZm9yd2FyZD0wfGNvYWRDYW5TdWJtaXQ9ZmFsc2V8aXNPcGVuTW9kaWZ5TG9nPTF8Zm9yd2FyZEJhY2s9MXxJc1N1Ym1pdGVkT3Bpbmlvbj0xfElzQmVGb3J3YXJkU3VibWl0PTB8aXNNb2RpZnlMb2c9fElzQmVGb3J3YXJkPTB8aXNNYWluU3VibWl0dGVkPWZhbHNlfGJpbGxpZD0yNHxJc0FscmVhZHlGb3J3YXJkPXx3ZmN1cnJyaWQ9NjE0OTQ3fGN1cnJlbnRzdGF0dXM9LTF8SXNUYWtpbmdPcGluaW9ucz0wfElzRnJvbVdGUmVtYXJrX1Q9MHxncm91cGRldGFpbGlkPTIzNDB8SXNGcm9tV0ZSZW1hcms9MHx0YWtpc3JlbWFyaz0wfHdvcmtmbG93dHlwZT01Nnxjb2FkaXNwZW5kaW5nPTB8bmV3ZG9jaWQ9fGludGVydmVub3JyaWdodD0wfGNhbkZvcndkPWZhbHNlfGRlbGV0ZWQ9MHxjb2FkaXNzdWJtaXRkZXNjPTB8',
        isFree: '0',
        currentNodeAttribute: '0',
        authStr: 'dmlld0NoYWluPTc5NDg3MXxtYWluaWQ9Nzk0ODcxfA==',
        margin: '30px 50px 30px 50px',
        f_weaver_belongto_usertype: '0',
        agentorByAgentId: -1,
        isagent: 0,
        currentnodeid: 1396,
        helpdocid: 0,
        iscowork: 0,
        billIncludePage: '',
        lastname: 'Developer 1',
        allowAllPersonGroup: true,
        isremark: '0',
        isCptwf: false,
        isOpenTextTab: false,
        agentType: 0,
        authSignatureStr: '9d4a58f2a5c03606a35557ab726d6dea',
        signatureSecretKey: '2097165a8e7cf95bcb7615186da648ad',
        custompage: {
          cssPage: [],
          jsPage: [],
          jspPage: [],
        },
        apiResultCacheKey: 1775550538054,
        signListType: false,
        fileViewUrl: '/spa/document/index2file.jsp',
        layoutconfigid: -1,
        ismodeCptwf: false,
        titlename: '流程:处理 - TestCosignOrConcurrent - 分叉中间点 <span id=\'requestmarkSpan\'>TESTA00009</span>',
        isWorkflowDoc: false,
        sendPage: '',
        intervenorright: 0,
        nodename: 'L1F',
        isHideInput: '',
        ismode: 0,
        selectNextFlow: '',
        openAutoForecast: '1',
        formid: -630,
        isNeedFlowFreeNodeTips: false,
        useInvoiceCloud: false,
        wfTestStr: '',
        newdocpath: '',
        itemCode: 'NODE',
        needconfirm: '',
        docViewUrl: '/spa/document/index.jsp',
        creatertype: 0,
        wfmonitor: false,
        toexcel: 0,
        nodeid: 1385,
        workflowid: 200,
        isbill: '1',
        docfileid: '',
        isrequest: '',
        f_weaver_belongto_userid: '26085',
        layoutversion: 2,
        showAutoForecastResult: '1,2',
        mouldCode: 'WORKFLOW',
        modeid: -1,
        requestid: 794871,
        creater: 23787,
        existSynergy: false,
        openDataVerify: '0',
        currentnodetype: '1',
        nodetype: '1',
        workflowname: 'TestCosignOrConcurrent',
        btnLabelName: {
          resourceTab: '相关资源',
          statusTab: '流程状态',
          shareTab: '流程共享',
          odocTab: '正文',
          communicationTab: '相关交流',
          formTab: '流程表单',
          picTab: '流程图',
        },
        isprint: '0',
        isHideArea: '',
        isviewonly: 0,
        isOpenCommunication: 0,
        showAI: 1,
        isaffirmanceSrc: '',
        isaffirmance: '',
        linkageUUID: '1189F522EE614AE2B555614C86C84D4B',
        iswfshare: '0',
        appDetachDisableAll: false,
        em_url: 'http://101.32.178.131:8999',
        em_url_open: 'https://dchappsuat.dch.com.hk:8444',
        desrequestid: 0,
        isSelfAuth: 1,
        isshared: '',
        requestType: 1,
        isSignInput: '1',
        hasFreeNode: false,
        takisremark: 0,
        currentUserid: 26085,
        isurger: false,
        user: {
          account: '',
          account_type: '0',
          admin: false,
          agent: 0,
          aliasname: '',
          assistantid: '',
          belongtoids: '',
          city: 0,
          contractdate: '',
          costcenterid: '',
          countryid: '1',
          currencyid: '',
          email: 'test@test.com',
          enddate: '',
          firstname: '',
          jobactivity: '',
          jobgroup: '',
          joblevel: '',
          jobtitle: '416',
          language: 7,
          lastlogindate: '2026-04-07',
          lastname: 'Developer 1',
          locationid: '283',
          loginid: 'dev1',
          loginip: '',
          logintype: '1',
          managerid: '23462',
          mergeFlag: true,
          mobile: '',
          mobilecall: '',
          needusb: 0,
          parentid: 0,
          postcode: '',
          province: 0,
          purchaselimit: '',
          pwd: '3DE3F9B25E1CC66976A603897BCFC44B',
          readonly: false,
          receiveaddress: '',
          remark: '',
          resourcetype: '',
          seclevel: '100',
          serial: '',
          sex: '0',
          startdate: '',
          status: 0,
          telephone: '',
          title: '',
          titlelocation: '',
          type: 0,
          uID: 26085,
          useAttrLanguage: false,
          userDepartment: 3255,
          userSubCompany1: 262,
          userSubCompany2: 0,
          userSubCompany3: 0,
          userSubCompany4: 0,
          username: 'Developer 1',
        },
        canSubmitToRejectNode: true,
      },
      fnaInfo: {
        invoiceCloud: false,
        belFna: false,
        belFnaMultiDimension: false,
      },
      submitParams: {
        'formid': -630,
        'isSubmitDirectNode': '',
        'openByDefaultBrowser': '',
        'iscreate': '0',
        'creatertype': 0,
        'isdialog': '1',
        'lastOperateDate': '2026-04-01',
        'createdoc': '',
        'nodeid': 1385,
        'workflowid': 200,
        'isbill': '1',
        'authStr': 'dmlld0NoYWluPTc5NDg3MXxtYWluaWQ9Nzk0ODcxfA==',
        'f_weaver_belongto_userid': '26085',
        'currenttime': '16:28:58',
        'f_weaver_belongto_usertype': '0',
        'agentorByAgentId': -1,
        'isMultiDoc': '',
        'inputcheck': '',
        'comemessage': '',
        'lastOperateTime': '17:28:27',
        'temphasUseTempletSucceed': '',
        'workflowRequestLogId': '',
        'edesign_layout': '',
        'requestid': 794871,
        'isremark': '0',
        'creater': 23787,
        'htmlfieldids': '',
        'SubmitToNodeid': '',
        'isCptwf': false,
        'isovertime': '',
        'agentType': 0,
        'authSignatureStr': '9d4a58f2a5c03606a35557ab726d6dea',
        'nodetype': '1',
        'needoutprint': '',
        'lastOperator': 26085,
        'topage': '',
        'isFormSignature': 0,
        'remindTypes': '',
        'fromFlowDoc': '',
        'RejectNodes': '',
        'linkageUUID': '1189F522EE614AE2B555614C86C84D4B',
        'billid': 24,
        'lastnodeid': '',
        'uploadType': '',
        '26085_794871_request_submit_token': 1775550538052,
        'isSignMustInput': '',
        'RejectToNodeid': '',
        'isWorkflowDoc': false,
        'src': '',
        'annexmaxUploadImageSize': '',
        'takisremark': 0,
        'workflowtype': '56',
        'remarkLocation': '',
        'needcheck': '',
        'needcheckLock': 'false',
        'selectfieldvalue': '',
        'RejectToType': '',
        'currentdate': '2026-04-07',
        'needwfback': '',
      },
      detailNum: 0,
      propFileCfg: {
        form_image_scalingRatio: '90',
        use_textarea_signinput: '0',
        form_image_handWritingColor: '#010102',
        handwriting_download_switch: '0',
        browser_color_controlByCell: '0',
        tri_formula_all: '0',
        tri_dataInput_main: '0',
        isImportBrowserField: '0',
        amount_convert_unit: '0',
        print_show_allTabs: '0',
        show_duration_log: '0',
        forward_submitaddshare: '1',
        workflowtodoc_useitext7: '0',
        open_server_eval: '0',
        workflowtodoc_watermark_fontcolor: '128,128,128',
        htmltopdf_orientation_landscape_wfids: 'all',
        workflow_pdffont_dir: '1~~weaversplit~~/font/workflow/pdf',
        form_openAutoForecast: '1',
        use_batch_submit_remark: '1',
        error_remind_workflow: '',
        support_html_textarea_field: 'field6_0',
        record_largefields_log: '0',
        form_image_handWritingBrush: 'md',
        files_link_onlyview: '0',
        file_download_use_docright: '0',
        req_async_saveoperationlog: '0',
        batch_print_control_width: '1000',
        mobile_show_radio: '0',
        wf_overtime_remind: '',
        close_duration_storage: '0',
        mobile_showchart: '0',
        req_async_updaterequestname: '0',
        request_batchsubmit_async: '1',
        wf_selectflow_signtype: '3',
        un_use_customize_browser_cache: '0',
        tri_rowRule_edit: '0',
        closeAutoComplete: '0',
        colRule_noRow_empty: '0',
        always_show_signinput: '1',
        autocomplete_change_name: '0',
        detail_hideArea_control: '0',
        tri_dataInput_detail: '0',
        tri_dateTime_detail: '1',
        workflowtodoc_watermark_fontsize: '12',
        nodeoperator_sortbyselectedkey: '0',
        htmltopdf_usewk: '1',
        split_req_linkageData: '0',
        batchPrintByModeid: '0',
        form_showAutoForecastResult: '1,2',
        detail_locked_button_row: '1',
        tri_fieldSql_detail: '1',
        form_image_handWritingMaxHeight: '',
        detail_prepage_size: '10',
        Intelligent_analysis_range: '0',
        print_signList_black_color: '0',
        rightbtn_enable_after_script: '0',
        bill_monthOrWeek_flow_flag: '1',
        mobile_show_checkbox: '0',
        enable_no_promptes_submit: '0',
        DatainputResultOutOfLimitNum: '2000',
        form_open_dataverify: '0',
        wf_selectflow_reject: '0',
        write_linkage_log_range: '',
        operated_show_type: '0',
        workflowtodoc_watermark_font: 'msyh.ttf',
        prohibitDownload: '0',
        tri_rowRule_view: '0',
        create_request_open_ofs: '1',
        FieldSqlResultOutOfLimitNum: '3000',
        script_debug: '0',
        form_customer_share: '1',
        form_allowAllPersion: '1',
        form_image_handWritingShowType: '1',
        form_sign_cellbr: '0',
        Intelligent_analysis_switch: '1',
        communicationInputOvertime: '10',
        form_image_handWritingMaxWidth: '',
        Intelligent_analysis_workflow_path: '',
        rowRule_addRow_empty: '0',
        export_excel_with_separated_sheets: '1',
        wbservice_delreq_verify_right: '1',
      },
      promptInfos: [],
      linkageCfg: {
        mainCalCfg: {},
        fieldSqlCfg: {},
        transTypeCfg: {},
        viewAttrCfg: {},
        formulaCfg: {
          formulas: [],
          systemdatas: {},
          files: [],
        },
        dataInputCfg: {},
        fieldMathCfg: {},
        fieldDateCfg: {},
        colCalCfg: {},
        rowCalCfg: {},
      },
      cellInfo: {
        nodeMarkContent: {},
        sysFieldInfo: {
          workflowname: 'TestCosignOrConcurrent',
          workflowdesc: '',
          workflowtype: 56,
          workflowtypename: '通用流程',
        },
        subPanelInfo: {},
        nodeNameInfo: {},
        labelInfo: {},
        printBreakRowInfo: [],
        existTextArea: false,
        nodeMarkGroup: [],
        mainRowFields: {
          main_row_2: [
            '-1',
          ],
          main_row_1: [
            '-2',
          ],
          main_row_6: [
            '29988',
          ],
          main_row_5: [
            '29995',
          ],
          main_row_4: [
            '29996',
          ],
          main_row_3: [
            '-9',
          ],
        },
        style: {
          layoutStyle: '<style type="text/css">.mainTd_1_0 span,.mainTd_1_0 div,.mainTd_1_0 input,.mainTd_1_0 textarea{\nfont-size:9pt; font-family:Microsoft YaHei;color:black;\n}\n.mainTd_1_0{\nheight:35px; background-color:#f4f4f4!important; border-top-width:1px; border-top-style:solid; border-top-color:#d9d9d9; border-left-width:1px; border-left-style:solid; border-left-color:#d9d9d9; border-right-width:1px; border-right-style:solid; border-right-color:#d9d9d9; border-bottom-width:1px; border-bottom-style:solid; border-bottom-color:#d9d9d9; vertical-align:middle; text-align:left; word-wrap:break-word; word-break:break-word;padding-left:8.0px; \n}\n.mainTd_1_1 span,.mainTd_1_1 div,.mainTd_1_1 input,.mainTd_1_1 textarea{\nfont-size:9pt; font-family:Microsoft YaHei;color:black;\n}\n.mainTd_1_1{\nheight:35px; background-color:#ffffff!important; border-top-width:1px; border-top-style:solid; border-top-color:#d9d9d9; border-left-width:1px; border-left-style:solid; border-left-color:#d9d9d9; border-right-width:1px; border-right-style:solid; border-right-color:#d9d9d9; border-bottom-width:1px; border-bottom-style:solid; border-bottom-color:#d9d9d9; vertical-align:middle; text-align:left; word-wrap:break-word; word-break:break-word;padding-left:8.0px; \n}\n.mainTd_2_0 span,.mainTd_2_0 div,.mainTd_2_0 input,.mainTd_2_0 textarea{\nfont-size:9pt; font-family:Microsoft YaHei;color:black;\n}\n.mainTd_2_0{\nheight:35px; background-color:#f4f4f4!important; border-top-width:1px; border-top-style:solid; border-top-color:#d9d9d9; border-left-width:1px; border-left-style:solid; border-left-color:#d9d9d9; border-right-width:1px; border-right-style:solid; border-right-color:#d9d9d9; border-bottom-width:1px; border-bottom-style:solid; border-bottom-color:#d9d9d9; vertical-align:middle; text-align:left; word-wrap:break-word; word-break:break-word;padding-left:8.0px; \n}\n.mainTd_2_1 span,.mainTd_2_1 div,.mainTd_2_1 input,.mainTd_2_1 textarea{\nfont-size:9pt; font-family:Microsoft YaHei;color:black;\n}\n.mainTd_2_1{\nheight:35px; background-color:#ffffff!important; border-top-width:1px; border-top-style:solid; border-top-color:#d9d9d9; border-left-width:1px; border-left-style:solid; border-left-color:#d9d9d9; border-right-width:1px; border-right-style:solid; border-right-color:#d9d9d9; border-bottom-width:1px; border-bottom-style:solid; border-bottom-color:#d9d9d9; vertical-align:middle; text-align:left; word-wrap:break-word; word-break:break-word;padding-left:8.0px; \n}\n.mainTd_3_0 span,.mainTd_3_0 div,.mainTd_3_0 input,.mainTd_3_0 textarea{\nfont-size:9pt; font-family:Microsoft YaHei;color:black;\n}\n.mainTd_3_0{\nheight:35px; background-color:#f4f4f4!important; border-top-width:1px; border-top-style:solid; border-top-color:#d9d9d9; border-left-width:1px; border-left-style:solid; border-left-color:#d9d9d9; border-right-width:1px; border-right-style:solid; border-right-color:#d9d9d9; border-bottom-width:1px; border-bottom-style:solid; border-bottom-color:#d9d9d9; vertical-align:middle; text-align:left; word-wrap:break-word; word-break:break-word;padding-left:8.0px; \n}\n.mainTd_3_1 span,.mainTd_3_1 div,.mainTd_3_1 input,.mainTd_3_1 textarea{\nfont-size:9pt; font-family:Microsoft YaHei;color:black;\n}\n.mainTd_3_1{\nheight:35px; background-color:#ffffff!important; border-top-width:1px; border-top-style:solid; border-top-color:#d9d9d9; border-left-width:1px; border-left-style:solid; border-left-color:#d9d9d9; border-right-width:1px; border-right-style:solid; border-right-color:#d9d9d9; border-bottom-width:1px; border-bottom-style:solid; border-bottom-color:#d9d9d9; vertical-align:middle; text-align:left; word-wrap:break-word; word-break:break-word;padding-left:8.0px; \n}\n.mainTd_4_0 span,.mainTd_4_0 div,.mainTd_4_0 input,.mainTd_4_0 textarea{\nfont-size:9pt; font-family:Microsoft YaHei;color:black;\n}\n.mainTd_4_0{\nheight:35px; background-color:#f4f4f4!important; border-top-width:1px; border-top-style:solid; border-top-color:#d9d9d9; border-left-width:1px; border-left-style:solid; border-left-color:#d9d9d9; border-right-width:1px; border-right-style:solid; border-right-color:#d9d9d9; border-bottom-width:1px; border-bottom-style:solid; border-bottom-color:#d9d9d9; vertical-align:middle; text-align:left; word-wrap:break-word; word-break:break-word;padding-left:8.0px; \n}\n.mainTd_4_1 span,.mainTd_4_1 div,.mainTd_4_1 input,.mainTd_4_1 textarea{\nfont-size:9pt; font-family:Microsoft YaHei;color:black;\n}\n.mainTd_4_1{\nheight:35px; background-color:#ffffff!important; border-top-width:1px; border-top-style:solid; border-top-color:#d9d9d9; border-left-width:1px; border-left-style:solid; border-left-color:#d9d9d9; border-right-width:1px; border-right-style:solid; border-right-color:#d9d9d9; border-bottom-width:1px; border-bottom-style:solid; border-bottom-color:#d9d9d9; vertical-align:middle; text-align:left; word-wrap:break-word; word-break:break-word;padding-left:8.0px; \n}\n.mainTd_5_0 span,.mainTd_5_0 div,.mainTd_5_0 input,.mainTd_5_0 textarea{\nfont-size:9pt; font-family:Microsoft YaHei;color:black;\n}\n.mainTd_5_0{\nheight:35px; background-color:#f4f4f4!important; border-top-width:1px; border-top-style:solid; border-top-color:#d9d9d9; border-left-width:1px; border-left-style:solid; border-left-color:#d9d9d9; border-right-width:1px; border-right-style:solid; border-right-color:#d9d9d9; border-bottom-width:1px; border-bottom-style:solid; border-bottom-color:#d9d9d9; vertical-align:middle; text-align:left; word-wrap:break-word; word-break:break-word;padding-left:8.0px; \n}\n.mainTd_5_1 span,.mainTd_5_1 div,.mainTd_5_1 input,.mainTd_5_1 textarea{\nfont-size:9pt; font-family:Microsoft YaHei;color:black;\n}\n.mainTd_5_1{\nheight:35px; background-color:#ffffff!important; border-top-width:1px; border-top-style:solid; border-top-color:#d9d9d9; border-left-width:1px; border-left-style:solid; border-left-color:#d9d9d9; border-right-width:1px; border-right-style:solid; border-right-color:#d9d9d9; border-bottom-width:1px; border-bottom-style:solid; border-bottom-color:#d9d9d9; vertical-align:middle; text-align:left; word-wrap:break-word; word-break:break-word;padding-left:8.0px; \n}\n.mainTd_6_0 span,.mainTd_6_0 div,.mainTd_6_0 input,.mainTd_6_0 textarea{\nfont-size:9pt; font-family:Microsoft YaHei;color:black;\n}\n.mainTd_6_0{\nheight:35px; background-color:#f4f4f4!important; border-top-width:1px; border-top-style:solid; border-top-color:#d9d9d9; border-left-width:1px; border-left-style:solid; border-left-color:#d9d9d9; border-right-width:1px; border-right-style:solid; border-right-color:#d9d9d9; border-bottom-width:1px; border-bottom-style:solid; border-bottom-color:#d9d9d9; vertical-align:middle; text-align:left; word-wrap:break-word; word-break:break-word;padding-left:8.0px; \n}\n.mainTd_6_1 span,.mainTd_6_1 div,.mainTd_6_1 input,.mainTd_6_1 textarea{\nfont-size:9pt; font-family:Microsoft YaHei;color:black;\n}\n.mainTd_6_1{\nheight:35px; background-color:#ffffff!important; border-top-width:1px; border-top-style:solid; border-top-color:#d9d9d9; border-left-width:1px; border-left-style:solid; border-left-color:#d9d9d9; border-right-width:1px; border-right-style:solid; border-right-color:#d9d9d9; border-bottom-width:1px; border-bottom-style:solid; border-bottom-color:#d9d9d9; vertical-align:middle; text-align:left; word-wrap:break-word; word-break:break-word;padding-left:8.0px; \n}\n.mainTd_0_0 span,.mainTd_0_0 div,.mainTd_0_0 input,.mainTd_0_0 textarea{\nfont-size:14pt;font-weight:bold; font-family:Microsoft YaHei;color:black;\n}\n.mainTd_0_0{\nheight:60px; vertical-align:middle; text-align:center; word-wrap:break-word; word-break:break-word;\n}\n</style>',
          scriptStyle: '<style type="text/css">.excelTempDiv{padding: 6px 35px}</style>',
        },
        existCurrentWfNodeMark: false,
        fieldCellInfo: {
          '29988': {
            symbol: 'main',
            orderid: 212,
            rowMark: 'main_row_6',
            rowspan: 1,
            colid: 1,
            rowid: 6,
          },
          '29995': {
            symbol: 'main',
            orderid: 182,
            rowMark: 'main_row_5',
            rowspan: 1,
            colid: 1,
            rowid: 5,
          },
          '29996': {
            symbol: 'main',
            orderid: 152,
            rowMark: 'main_row_4',
            rowspan: 1,
            colid: 1,
            rowid: 4,
          },
          '-1': {
            symbol: 'main',
            orderid: 92,
            rowMark: 'main_row_2',
            rowspan: 1,
            colid: 1,
            rowid: 2,
          },
          '-2': {
            symbol: 'main',
            orderid: 62,
            rowMark: 'main_row_1',
            rowspan: 1,
            colid: 1,
            rowid: 1,
          },
          '-9': {
            symbol: 'main',
            orderid: 122,
            rowMark: 'main_row_3',
            rowspan: 1,
            colid: 1,
            rowid: 3,
          },
        },
      },
      promptInfo: {},
      browserInfo: {},
      datajson: {
        eformdesign: {
          etables: {
            emaintable: {
              rowheads: {
                row_0: '60',
                row_1: '35',
                row_2: '35',
                row_3: '35',
                row_4: '35',
                row_5: '35',
                row_6: '35',
              },
              colheads: {
                col_0: '250',
                col_1: '*',
              },
              ec: [
                {
                  id: '1,0',
                  backgroundColor: '#f4f4f4',
                  etype: '2',
                  field: '-2',
                  font: {
                    'valign': 'middle',
                    'autoWrap': 'true',
                    'text-align': 'left',
                  },
                  etxtindent: '1',
                  eborder: [
                    {
                      color: '#d9d9d9',
                      kind: 'top',
                      style: '1',
                    },
                    {
                      color: '#d9d9d9',
                      kind: 'left',
                      style: '1',
                    },
                    {
                      color: '#d9d9d9',
                      kind: 'right',
                      style: '1',
                    },
                    {
                      color: '#d9d9d9',
                      kind: 'bottom',
                      style: '1',
                    },
                  ],
                  evalue: '紧急程度',
                },
                {
                  id: '1,1',
                  backgroundColor: '#ffffff',
                  etype: '3',
                  field: '-2',
                  font: {
                    'valign': 'middle',
                    'autoWrap': 'true',
                    'text-align': 'left',
                  },
                  etxtindent: '1',
                  eborder: [
                    {
                      color: '#d9d9d9',
                      kind: 'top',
                      style: '1',
                    },
                    {
                      color: '#d9d9d9',
                      kind: 'left',
                      style: '1',
                    },
                    {
                      color: '#d9d9d9',
                      kind: 'right',
                      style: '1',
                    },
                    {
                      color: '#d9d9d9',
                      kind: 'bottom',
                      style: '1',
                    },
                  ],
                  evalue: '紧急程度',
                },
                {
                  id: '2,0',
                  backgroundColor: '#f4f4f4',
                  etype: '2',
                  field: '-1',
                  font: {
                    'valign': 'middle',
                    'autoWrap': 'true',
                    'text-align': 'left',
                  },
                  etxtindent: '1',
                  eborder: [
                    {
                      color: '#d9d9d9',
                      kind: 'top',
                      style: '1',
                    },
                    {
                      color: '#d9d9d9',
                      kind: 'left',
                      style: '1',
                    },
                    {
                      color: '#d9d9d9',
                      kind: 'right',
                      style: '1',
                    },
                    {
                      color: '#d9d9d9',
                      kind: 'bottom',
                      style: '1',
                    },
                  ],
                  evalue: '标题',
                },
                {
                  id: '2,1',
                  backgroundColor: '#ffffff',
                  etype: '3',
                  field: '-1',
                  font: {
                    'valign': 'middle',
                    'autoWrap': 'true',
                    'text-align': 'left',
                  },
                  etxtindent: '1',
                  eborder: [
                    {
                      color: '#d9d9d9',
                      kind: 'top',
                      style: '1',
                    },
                    {
                      color: '#d9d9d9',
                      kind: 'left',
                      style: '1',
                    },
                    {
                      color: '#d9d9d9',
                      kind: 'right',
                      style: '1',
                    },
                    {
                      color: '#d9d9d9',
                      kind: 'bottom',
                      style: '1',
                    },
                  ],
                  evalue: '标题',
                },
                {
                  id: '3,0',
                  backgroundColor: '#f4f4f4',
                  etype: '2',
                  field: '-9',
                  font: {
                    'valign': 'middle',
                    'autoWrap': 'true',
                    'text-align': 'left',
                  },
                  etxtindent: '1',
                  eborder: [
                    {
                      color: '#d9d9d9',
                      kind: 'top',
                      style: '1',
                    },
                    {
                      color: '#d9d9d9',
                      kind: 'left',
                      style: '1',
                    },
                    {
                      color: '#d9d9d9',
                      kind: 'right',
                      style: '1',
                    },
                    {
                      color: '#d9d9d9',
                      kind: 'bottom',
                      style: '1',
                    },
                  ],
                  evalue: '打印次数',
                },
                {
                  id: '3,1',
                  backgroundColor: '#ffffff',
                  etype: '3',
                  field: '-9',
                  font: {
                    'valign': 'middle',
                    'autoWrap': 'true',
                    'text-align': 'left',
                  },
                  etxtindent: '1',
                  eborder: [
                    {
                      color: '#d9d9d9',
                      kind: 'top',
                      style: '1',
                    },
                    {
                      color: '#d9d9d9',
                      kind: 'left',
                      style: '1',
                    },
                    {
                      color: '#d9d9d9',
                      kind: 'right',
                      style: '1',
                    },
                    {
                      color: '#d9d9d9',
                      kind: 'bottom',
                      style: '1',
                    },
                  ],
                  evalue: '打印次数',
                },
                {
                  id: '4,0',
                  backgroundColor: '#f4f4f4',
                  etype: '2',
                  field: '29996',
                  font: {
                    'valign': 'middle',
                    'autoWrap': 'true',
                    'text-align': 'left',
                  },
                  etxtindent: '1',
                  eborder: [
                    {
                      color: '#d9d9d9',
                      kind: 'top',
                      style: '1',
                    },
                    {
                      color: '#d9d9d9',
                      kind: 'left',
                      style: '1',
                    },
                    {
                      color: '#d9d9d9',
                      kind: 'right',
                      style: '1',
                    },
                    {
                      color: '#d9d9d9',
                      kind: 'bottom',
                      style: '1',
                    },
                  ],
                  evalue: 'Image',
                },
                {
                  id: '4,1',
                  backgroundColor: '#ffffff',
                  etype: '3',
                  field: '29996',
                  font: {
                    'valign': 'middle',
                    'autoWrap': 'true',
                    'text-align': 'left',
                  },
                  etxtindent: '1',
                  eborder: [
                    {
                      color: '#d9d9d9',
                      kind: 'top',
                      style: '1',
                    },
                    {
                      color: '#d9d9d9',
                      kind: 'left',
                      style: '1',
                    },
                    {
                      color: '#d9d9d9',
                      kind: 'right',
                      style: '1',
                    },
                    {
                      color: '#d9d9d9',
                      kind: 'bottom',
                      style: '1',
                    },
                  ],
                  evalue: 'Image',
                },
                {
                  id: '5,0',
                  backgroundColor: '#f4f4f4',
                  etype: '2',
                  field: '29995',
                  font: {
                    'valign': 'middle',
                    'autoWrap': 'true',
                    'text-align': 'left',
                  },
                  etxtindent: '1',
                  eborder: [
                    {
                      color: '#d9d9d9',
                      kind: 'top',
                      style: '1',
                    },
                    {
                      color: '#d9d9d9',
                      kind: 'left',
                      style: '1',
                    },
                    {
                      color: '#d9d9d9',
                      kind: 'right',
                      style: '1',
                    },
                    {
                      color: '#d9d9d9',
                      kind: 'bottom',
                      style: '1',
                    },
                  ],
                  evalue: 'File',
                },
                {
                  id: '5,1',
                  backgroundColor: '#ffffff',
                  etype: '3',
                  field: '29995',
                  font: {
                    'valign': 'middle',
                    'autoWrap': 'true',
                    'text-align': 'left',
                  },
                  etxtindent: '1',
                  eborder: [
                    {
                      color: '#d9d9d9',
                      kind: 'top',
                      style: '1',
                    },
                    {
                      color: '#d9d9d9',
                      kind: 'left',
                      style: '1',
                    },
                    {
                      color: '#d9d9d9',
                      kind: 'right',
                      style: '1',
                    },
                    {
                      color: '#d9d9d9',
                      kind: 'bottom',
                      style: '1',
                    },
                  ],
                  evalue: 'File',
                },
                {
                  id: '6,0',
                  backgroundColor: '#f4f4f4',
                  etype: '2',
                  field: '29988',
                  font: {
                    'valign': 'middle',
                    'autoWrap': 'true',
                    'text-align': 'left',
                  },
                  etxtindent: '1',
                  eborder: [
                    {
                      color: '#d9d9d9',
                      kind: 'top',
                      style: '1',
                    },
                    {
                      color: '#d9d9d9',
                      kind: 'left',
                      style: '1',
                    },
                    {
                      color: '#d9d9d9',
                      kind: 'right',
                      style: '1',
                    },
                    {
                      color: '#d9d9d9',
                      kind: 'bottom',
                      style: '1',
                    },
                  ],
                  evalue: 'Case&nbsp;No',
                },
                {
                  id: '6,1',
                  backgroundColor: '#ffffff',
                  etype: '3',
                  field: '29988',
                  font: {
                    'valign': 'middle',
                    'autoWrap': 'true',
                    'text-align': 'left',
                  },
                  etxtindent: '1',
                  eborder: [
                    {
                      color: '#d9d9d9',
                      kind: 'top',
                      style: '1',
                    },
                    {
                      color: '#d9d9d9',
                      kind: 'left',
                      style: '1',
                    },
                    {
                      color: '#d9d9d9',
                      kind: 'right',
                      style: '1',
                    },
                    {
                      color: '#d9d9d9',
                      kind: 'bottom',
                      style: '1',
                    },
                  ],
                  evalue: 'Case&nbsp;No',
                },
                {
                  id: '0,0',
                  etype: '1',
                  colspan: '2',
                  font: {
                    'font-size': '14pt',
                    'valign': 'middle',
                    'bold': 'true',
                    'text-align': 'center',
                  },
                  evalue: 'TestCosignOrConcurrent',
                },
              ],
            },
          },
          eattr: {
            wfid: '200',
            nodeid: '1385',
            formid: '-630',
            isbill: '1',
          },
        },
      },
      durationTime: 86,
    },
    logInfo: {
      maxrequestlogid: '',
      loglist: [
        {
          handWrittenSignDoc: [],
          displaytype: '0',
          checkSuccess: '-1',
          isexsAgent: false,
          displaybyagentname: '',
          logtype: '0',
          isProtected: '0',
          signnaturImgHeight: 60,
          isinneruser: true,
          pgflag: '1',
          isReference: true,
          forwardMenuName: '转发',
          displayid: '26085',
          log_agentorbyagentid: '-1',
          log_nodename: 'L1B',
          displaydepname: 'Prof Svc-Low Code Platform',
          userimg: '',
          showMoreReceiveBtn: false,
          speechAttachmetnDatas: [],
          forward: 0,
          log_operatedate: '2026-04-01',
          remarkLocation: '',
          displaydepid: '3255',
          receiveUser: 'Wait For The Merger ',
          log_operatetime: '17:28:27',
          img_path: '/messager/images/icon_m_wev8.jpg',
          operationname: '批准',
          displayname: 'Developer 1',
          logid: '240147',
          log_remarkHtml: '<p><img alt="" src="/weaver/weaver.file.FileDownload?fileid=a258b780b27908cd6d3e0e98e535e76f3002a396cada1bebd7739a1f4333371275a0b0a6f7c7a64d8def236dde105d540b5905a11971c0d38" /></p><p>&nbsp;</p><p>&nbsp;</p><p><span style="font-size:48px;"><span style="font-family:Comic Sans MS;"><b>i am styled text</b></span></span></p>',
          receiveUserCount: 1,
          tempremark: '',
        },
        {
          handWrittenSignDoc: [],
          displaytype: '2',
          checkSuccess: '-1',
          isexsAgent: false,
          displaybyagentname: '',
          logtype: '2',
          isProtected: '0',
          signnaturImgHeight: 60,
          isinneruser: true,
          pgflag: '1',
          isReference: true,
          forwardMenuName: '转发',
          displayid: '0',
          log_agentorbyagentid: '-1',
          log_nodename: 'L1',
          displaydepname: '',
          userimg: '',
          showMoreReceiveBtn: false,
          speechAttachmetnDatas: [],
          forward: 0,
          log_operatedate: '2026-04-01',
          remarkLocation: 'null',
          displaydepid: '',
          receiveUser: 'Chan Chun Hong Felix,Developer 1',
          log_operatetime: '16:41:17',
          img_path: '/messager/images/robot.png',
          operationname: '提交',
          displayname: '流程机器人',
          logid: '240144',
          log_remarkHtml: 'Intelligent processing of process robot',
          receiveUserCount: 2,
          tempremark: '',
        },
        {
          handWrittenSignDoc: [],
          displaytype: '0',
          checkSuccess: '-1',
          isexsAgent: false,
          displaybyagentname: '',
          logtype: '2',
          isProtected: '0',
          signnaturImgHeight: 60,
          isinneruser: true,
          pgflag: '1',
          isReference: true,
          forwardMenuName: '转发',
          displayid: '23787',
          log_agentorbyagentid: '-1',
          log_nodename: '创建1',
          displaydepname: 'Prof Svc-Low Code Platform',
          userimg: '',
          showMoreReceiveBtn: false,
          speechAttachmetnDatas: [],
          forward: 0,
          log_operatedate: '2026-04-01',
          remarkLocation: '',
          displaydepid: '3255',
          receiveUser: '流程机器人',
          log_operatetime: '16:41:15',
          img_path: '/messager/images/icon_m_wev8.jpg',
          operationname: '提交',
          displayname: 'Chan Chun Hong Felix',
          logid: '240143',
          log_remarkHtml: '<p><img alt="" src="/weaver/weaver.file.FileDownload?fileid=ad9e63ea2aca8a7b19de9c9028fe3974cf8c31f9b5d65b27e26d82d28912f0bd8a5fdb495e41bddda00fde34b4dc55cfab102e90485cf827b" />芟屏</p>',
          receiveUserCount: 1,
          tempremark: '',
        },
      ],
      totalCount: 3,
      isEnd: true,
    },
  }
},
)
